In [1]:
library('SelectSim')
library('tidyverse')

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
sessionInfo()

R version 4.4.2 (2024-10-31)
Platform: x86_64-conda-linux-gnu
Running under: AlmaLinux 9.3 (Shamrock Pampas Cat)

Matrix products: default
BLAS/LAPACK: /mnt/ndata/arvind/envs/selectsim_R/lib/libopenblasp-r0.3.29.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Europe/Zurich
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] lubridate_1.9.4   forcats_1.0.0     stringr_1.5.1     dplyr_1.1.4
 [5] purrr_1.0.4       readr_2.1.5       tidyr_1.3.1       tibble_3.2.1
 [9] ggplot2_3.5.1     tidyverse_2.0.0   SelectSim_0.0.1.5

loaded via a namespace (and not attached):
 [1] gtable_0.3.6       rstatix_0.7.2      lattice_0.22-6     tzdb_0.5.0
 [5] vctrs_0.6.5        tools_4.4.2        generics_0.1.3     parallel_4.4.2
 [9] pkgconfig_2.0.3    Matrix_1.7-3       ggridges_0.5.6     rngtools_1.5.2
[13] RcppParallel_5.1.9 uuid_1.2-1         lifecycle_1.0.4    compiler_4.4.2
[17] tictoc_1.2.1       munsell_0.5.1      repr_1.1.7         codetools_0.2-20
[21] carData_3.0-5      htmltools_0.5.8.1  Formula_1.2-5      pillar_1.10.1
[25] car_3.1-3          ggpubr_0.6.0       crayon_1.5.3       doRNG_1.8.6.2
[29] iterators_1.0.14   abind_1.4-5        foreach_1.5.2      tidyselect_1.2.1
[33] digest_0.6.37      stringi_1.8.7      reshape2_1.4.4     fastmap_1.2.0
[37] grid_4.4.2         colorspace_2.1-1   cli_3.6.4          magrittr_2.0.3
[41] base64enc_0.1-3    Rfast_2.1.0        IRdisplay_1.1      broom_1.0.8
[45] withr_3.0.2        scales_1.3.0       backports_1.5.0    IRkernel_1.3.2
[49] RcppZiggurat_0.1.8 timechange_0.3.0   pbdZMQ_0.3-13      ggsignif_0.6.4
[53] hms_1.1.3          evaluate_1.0.3     doParallel_1.0.17  rlang_1.1.5
[57] Rcpp_1.0.14        glue_1.8.0         jsonlite_2.0.0     R6_2.6.1
[61] plyr_1.8.9

#  Functions

In [84]:
# Filter the pan_can_run data object to required needs.
filter_run_data <- function(run_data,gene_order,sample_order){
    final_run_data<-run_data
    final_run_data$M$M$missense<-as.matrix(run_data$M$M$missense[gene_order,sample_order])
    final_run_data$M$M$truncating<-run_data$M$M$truncating[gene_order,sample_order]
    final_run_data$alteration.class<- run_data$alteration.class[gene_order]
    final_run_data$sample.class<-run_data$sample.class[sample_order]
    final_run_data$M$tmb$missense<-run_data$M$tmb$missense[sample_order,]
    final_run_data$M$tmb$truncating<-run_data$M$tmb$truncating[sample_order,]
    return(final_run_data)
}

# Metadata

In [4]:
all_merged_metdata <- readRDS(file='/mnt/ndata/arvind/co_mutation_project/data/processed/all_merged_data_genie_v15.rds')
genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples<-readRDS(file='/mnt/ndata/arvind/co_mutation_project/data/processed/genie/msk_one_patient_one_sample_final.rds')
genie_metadata_15_dfci_with_mutation_selected_final_atleast_100_samples<-readRDS(file='/mnt/ndata/arvind/co_mutation_project/data/processed/genie/dfci_one_patient_one_sample_final.rds')

In [5]:
msk_run_gene_list <- readRDS(file='/mnt/ndata/arvind/co_mutation_project/analysis/catalogue/data/msk_oncokb_gene_run_list.rds')

In [6]:
head(all_merged_metdata,1)

  sample          class tumor_run oncotree cancer_type              race
1 TCGA-OR-A5J5-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
  cohort tumor_run_mapped Tissue        final_tumor_run_mapped
1 TCGA   No mapping       Adrenal Gland ACC

In [7]:
str(msk_run_gene_list)

List of 6
 $ all   : chr [1:202] "MTOR" "NRAS" "NTRK1" "SDHC" ...
 $ p_505 : chr [1:327] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_468 : chr [1:306] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_410 : chr [1:282] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_341 : chr [1:249] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_heme: chr [1:267] "MTOR" "NRAS" "CD58" "NTRK1" ...

# Pan-Cancer Runs

## MSK hotspot run (all)

In [87]:
msk_run_p_data <- readRDS('../data/pan_can_msk_primary_run_hotspot_v15.rds')

In [88]:
str(msk_run_p_data)

List of 3
 $ M               :List of 2
  ..$ M  :List of 2
  .. ..$ missense  : num [1:411, 1:27825] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:411] "AKT1" "ALK" "APC" "AR" ...
  .. .. .. ..$ : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  .. ..$ truncating: num [1:411, 1:27825] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:411] "AKT1" "ALK" "APC" "AR" ...
  .. .. .. ..$ : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  ..$ tmb:List of 2
  .. ..$ missense  :'data.frame':	27825 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  .. .. ..$ mutation: num [1:27825] 4 4 1 0 4 2 3 3 2 3 ...
  .. ..$ truncating:'data.frame':	27825 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  .. .. ..$ mutation: num [1:27825] 1 3 0 3 1 0 0 0 0 2 ...
 $ sample.class    : Named chr [1:27825] "Glioma_low_grade" "Glioma_low_grade" "Glioma_low_grade" "Glioma_low_grade" ...
  ..- attr(*, "names")= chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
 $ alteration.class: Named chr [1:411] "MUT" "MUT" "MUT" "MUT" ...
  ..- attr(*, "names")= chr [1:411] "AKT1" "ALK" "APC" "AR" ...

In [89]:
table(msk_run_p_data$sample.class)
length(table(msk_run_p_data$sample.class))

            ACRM             ACYC              AML             ANSC
              39               67              118               96
            APAD             BLCA              BLL             CCOV
              60             1273              117              105
            CESC             CHOL           CLLSLL           CRC_HM
             108              107              265              610
          CRC_LM             CSCC             DDLS         DLBCLNOS
            3530               67              117              357
            EHCH             ESCA             ESCC               FL
              81              740               83              321
            GBAD              GBC              GBM             GIST
              60               62             1045              354
Glioma_low_grade              HCC            HGSFT            HGSOC
             436              264               88              610
            HNSC              IDC             IHCH              ILC
             236             2339              417              288
           LGSOC              LMS             LUAD             LUNE
              46              115             3049               51
            LUSC             MAAP              MBN              MCC
             543               61               99               55
             MCL              MEL              MFH             MGCT
             167              389              148               66
             MPN              NBL            NSCLC               OS
              85              131              207               64
            PAAD            PANET          PLEMESO             PRAD
            1834              118              126             1805
             RCC          SARCNOS             SCLC              SEM
             520              191              195               71
            STAD             THAP             THPA             THPD
             411               81              154               98
         UCEC_HM          UCEC_LM              UCS             ULMS
             510             1055              226               96
              UM              USC             UTUC
              47              336              215

[1] 67

In [90]:
str(msk_run_p_data$sample.class)

 Named chr [1:27825] "Glioma_low_grade" "Glioma_low_grade" ...
 - attr(*, "names")= chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...

In [91]:
genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% head(1)

  PATIENT_ID          SEX    PRIMARY_RACE ETHNICITY                CENTER
1 GENIE-MSK-P-0000223 Female White        Non-Spanish/non-Hispanic MSK
  INT_CONTACT INT_DOD YEAR_CONTACT DEAD YEAR_DEATH ⋯ ONCOTREE_CODE SAMPLE_TYPE
1 11142       11142   2016         TRUE 2016       ⋯ AASTR         Primary
  SEQ_ASSAY_ID  CANCER_TYPE CANCER_TYPE_DETAILED   SAMPLE_TYPE_DETAILED class
1 MSK-IMPACT341 Glioma      Anaplastic Astrocytoma Primary tumor        AASTR
  Tumor_run_group final_class      final_run_group
1 AASTR           Glioma_low_grade Glioma

In [92]:
str(msk_run_gene_list)

List of 6
 $ all   : chr [1:202] "MTOR" "NRAS" "NTRK1" "SDHC" ...
 $ p_505 : chr [1:327] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_468 : chr [1:306] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_410 : chr [1:282] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_341 : chr [1:249] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_heme: chr [1:267] "MTOR" "NRAS" "CD58" "NTRK1" ...

In [93]:
assay_id<-unique(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples$SEQ_ASSAY_ID)

In [94]:
assay_id

[1] "MSK-IMPACT341"       "MSK-IMPACT410"       "MSK-IMPACT468"
[4] "MSK-IMPACT505"       "MSK-IMPACT-HEME-400" "MSK-IMPACT-HEME-468"

In [95]:
consider_hotspot_genes<-readRDS(file='../data/pan_can_msk_hotspot_genes.rds')

In [96]:
all_panel_genes<- intersect(msk_run_gene_list$all,rownames(msk_run_p_data$M$M$missense))
all_panel_genes <- c(all_panel_genes,consider_hotspot_genes)

In [97]:
length(all_panel_genes)

[1] 217

In [98]:
samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
          filter(SAMPLE_TYPE=='Primary'))$SAMPLE_ID
temp<- filter_run_data(run_data = msk_run_p_data,
                       gene_order = all_panel_genes,
                       sample_order =samples )

In [99]:
str(temp)

List of 3
 $ M               :List of 2
  ..$ M  :List of 2
  .. ..$ missense  : num [1:217, 1:27825] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:217] "MTOR" "NRAS" "NTRK1" "SDHC" ...
  .. .. .. ..$ : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  .. ..$ truncating: num [1:217, 1:27825] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:217] "MTOR" "NRAS" "NTRK1" "SDHC" ...
  .. .. .. ..$ : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  ..$ tmb:List of 2
  .. ..$ missense  :'data.frame':	27825 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  .. .. ..$ mutation: num [1:27825] 4 4 1 0 4 2 3 3 2 3 ...
  .. ..$ truncating:'data.frame':	27825 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  .. .. ..$ mutation: num [1:27825] 1 3 0 3 1 0 0 0 0 2 ...
 $ sample.class    : Named chr [1:27825] "Glioma_low_grade" "Glioma_low_grade" "Glioma_low_grade" "Glioma_low_grade" ...
  ..- attr(*, "names")= chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
 $ alteration.class: Named chr [1:217] "MUT" "MUT" "MUT" "MUT" ...
  ..- attr(*, "names")= chr [1:217] "MTOR" "NRAS" "NTRK1" "SDHC" ...

In [100]:
'KRAS' %in% rownames(temp$M$M$missense)
'EGFR' %in% rownames(temp$M$M$missense)
'PIK3CA' %in% rownames(temp$M$M$missense)
'BRAF' %in% rownames(temp$M$M$missense)

[1] FALSE

[1] FALSE

[1] FALSE

[1] FALSE

In [101]:
label<-paste('../data/','msk_panel_all','_primary_hotspot_run_data.rds',sep="")
saveRDS(temp,file = label,compress = TRUE)

In [103]:
msk_result <- selectX(M = temp$M,
                sample.class = temp$sample.class,
                alteration.class = temp$alteration.class,
                n.cores = 15,
                min.freq = round(0.001*length(temp$sample.class)),
                n.permut = 1000,
                lambda = 0.3,
                tao = 1,
                save.object = FALSE,
                verbose = FALSE,
                estimate_pairwise = FALSE,
                maxFDR = 0.25,
                seed = 42)
label<-paste('../results/','msk_panel_','all','_hotspot_result.rds',sep="")
saveRDS(msk_result,file = label,compress = TRUE)
rm(msk_result)

Total Time: 520.251 sec elapsed

## MSK hotspot run (p468)

In [104]:
msk_run_p_data <- readRDS('../data/pan_can_msk_primary_run_hotspot_v15.rds')

In [105]:
str(msk_run_p_data)

List of 3
 $ M               :List of 2
  ..$ M  :List of 2
  .. ..$ missense  : num [1:411, 1:27825] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:411] "AKT1" "ALK" "APC" "AR" ...
  .. .. .. ..$ : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  .. ..$ truncating: num [1:411, 1:27825] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:411] "AKT1" "ALK" "APC" "AR" ...
  .. .. .. ..$ : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  ..$ tmb:List of 2
  .. ..$ missense  :'data.frame':	27825 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  .. .. ..$ mutation: num [1:27825] 4 4 1 0 4 2 3 3 2 3 ...
  .. ..$ truncating:'data.frame':	27825 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  .. .. ..$ mutation: num [1:27825] 1 3 0 3 1 0 0 0 0 2 ...
 $ sample.class    : Named chr [1:27825] "Glioma_low_grade" "Glioma_low_grade" "Glioma_low_grade" "Glioma_low_grade" ...
  ..- attr(*, "names")= chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
 $ alteration.class: Named chr [1:411] "MUT" "MUT" "MUT" "MUT" ...
  ..- attr(*, "names")= chr [1:411] "AKT1" "ALK" "APC" "AR" ...

In [106]:
table(msk_run_p_data$sample.class)
length(table(msk_run_p_data$sample.class))

            ACRM             ACYC              AML             ANSC
              39               67              118               96
            APAD             BLCA              BLL             CCOV
              60             1273              117              105
            CESC             CHOL           CLLSLL           CRC_HM
             108              107              265              610
          CRC_LM             CSCC             DDLS         DLBCLNOS
            3530               67              117              357
            EHCH             ESCA             ESCC               FL
              81              740               83              321
            GBAD              GBC              GBM             GIST
              60               62             1045              354
Glioma_low_grade              HCC            HGSFT            HGSOC
             436              264               88              610
            HNSC              IDC             IHCH              ILC
             236             2339              417              288
           LGSOC              LMS             LUAD             LUNE
              46              115             3049               51
            LUSC             MAAP              MBN              MCC
             543               61               99               55
             MCL              MEL              MFH             MGCT
             167              389              148               66
             MPN              NBL            NSCLC               OS
              85              131              207               64
            PAAD            PANET          PLEMESO             PRAD
            1834              118              126             1805
             RCC          SARCNOS             SCLC              SEM
             520              191              195               71
            STAD             THAP             THPA             THPD
             411               81              154               98
         UCEC_HM          UCEC_LM              UCS             ULMS
             510             1055              226               96
              UM              USC             UTUC
              47              336              215

[1] 67

In [107]:
str(msk_run_p_data$sample.class)

 Named chr [1:27825] "Glioma_low_grade" "Glioma_low_grade" ...
 - attr(*, "names")= chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...

In [108]:
genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% head(1)

  PATIENT_ID          SEX    PRIMARY_RACE ETHNICITY                CENTER
1 GENIE-MSK-P-0000223 Female White        Non-Spanish/non-Hispanic MSK
  INT_CONTACT INT_DOD YEAR_CONTACT DEAD YEAR_DEATH ⋯ ONCOTREE_CODE SAMPLE_TYPE
1 11142       11142   2016         TRUE 2016       ⋯ AASTR         Primary
  SEQ_ASSAY_ID  CANCER_TYPE CANCER_TYPE_DETAILED   SAMPLE_TYPE_DETAILED class
1 MSK-IMPACT341 Glioma      Anaplastic Astrocytoma Primary tumor        AASTR
  Tumor_run_group final_class      final_run_group
1 AASTR           Glioma_low_grade Glioma

In [109]:
str(msk_run_gene_list)

List of 6
 $ all   : chr [1:202] "MTOR" "NRAS" "NTRK1" "SDHC" ...
 $ p_505 : chr [1:327] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_468 : chr [1:306] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_410 : chr [1:282] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_341 : chr [1:249] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_heme: chr [1:267] "MTOR" "NRAS" "CD58" "NTRK1" ...

In [110]:
assay_id<-unique(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples$SEQ_ASSAY_ID)

In [111]:
assay_id

[1] "MSK-IMPACT341"       "MSK-IMPACT410"       "MSK-IMPACT468"
[4] "MSK-IMPACT505"       "MSK-IMPACT-HEME-400" "MSK-IMPACT-HEME-468"

In [112]:
consider_hotspot_genes<-readRDS(file='../data/pan_can_msk_hotspot_genes.rds')

In [113]:
all_panel_genes<- intersect(msk_run_gene_list$p_468,rownames(msk_run_p_data$M$M$missense))
all_panel_genes <- c(all_panel_genes,consider_hotspot_genes)

In [114]:
length(all_panel_genes)

[1] 321

In [115]:
samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                  filter(SAMPLE_TYPE=='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT468') %>% 
                  group_by(final_class) %>%
                  filter(n()>=30) %>%
                  ungroup())$SAMPLE_ID
temp<- filter_run_data(run_data = msk_run_p_data,
                       gene_order = all_panel_genes,
                       sample_order =samples )

In [116]:
str(temp)

List of 3
 $ M               :List of 2
  ..$ M  :List of 2
  .. ..$ missense  : num [1:321, 1:13876] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:321] "MTOR" "NRAS" "RIT1" "NTRK1" ...
  .. .. .. ..$ : chr [1:13876] "GENIE-MSK-P-0014498-T01-IM6" "GENIE-MSK-P-0016576-T01-IM6" "GENIE-MSK-P-0015044-T01-IM6" "GENIE-MSK-P-0016257-T01-IM6" ...
  .. ..$ truncating: num [1:321, 1:13876] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:321] "MTOR" "NRAS" "RIT1" "NTRK1" ...
  .. .. .. ..$ : chr [1:13876] "GENIE-MSK-P-0014498-T01-IM6" "GENIE-MSK-P-0016576-T01-IM6" "GENIE-MSK-P-0015044-T01-IM6" "GENIE-MSK-P-0016257-T01-IM6" ...
  ..$ tmb:List of 2
  .. ..$ missense  :'data.frame':	13876 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:13876] "GENIE-MSK-P-0014498-T01-IM6" "GENIE-MSK-P-0016576-T01-IM6" "GENIE-MSK-P-0015044-T01-IM6" "GENIE-MSK-P-0016257-T01-IM6" ...
  .. .. ..$ mutation: num [1:13876] 5 9 2 2 1 4 3 3 1 2 ...
  .. ..$ truncating:'data.frame':	13876 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:13876] "GENIE-MSK-P-0014498-T01-IM6" "GENIE-MSK-P-0016576-T01-IM6" "GENIE-MSK-P-0015044-T01-IM6" "GENIE-MSK-P-0016257-T01-IM6" ...
  .. .. ..$ mutation: num [1:13876] 0 1 2 1 0 0 1 1 0 1 ...
 $ sample.class    : Named chr [1:13876] "Glioma_low_grade" "Glioma_low_grade" "Glioma_low_grade" "Glioma_low_grade" ...
  ..- attr(*, "names")= chr [1:13876] "GENIE-MSK-P-0014498-T01-IM6" "GENIE-MSK-P-0016576-T01-IM6" "GENIE-MSK-P-0015044-T01-IM6" "GENIE-MSK-P-0016257-T01-IM6" ...
 $ alteration.class: Named chr [1:321] "MUT" "MUT" "MUT" "MUT" ...
  ..- attr(*, "names")= chr [1:321] "MTOR" "NRAS" "RIT1" "NTRK1" ...

In [117]:
'KRAS' %in% rownames(temp$M$M$missense)
'EGFR' %in% rownames(temp$M$M$missense)
'PIK3CA' %in% rownames(temp$M$M$missense)
'BRAF' %in% rownames(temp$M$M$missense)
'SMAD4' %in% rownames(temp$M$M$missense)
'CDKN2A' %in% rownames(temp$M$M$missense)

[1] FALSE

[1] FALSE

[1] FALSE

[1] FALSE

[1] TRUE

[1] TRUE

In [118]:
label<-paste('../data/','msk_panel_p_468','_primary_hotspot_run_data.rds',sep="")
saveRDS(temp,file = label,compress = TRUE)

In [119]:
msk_result <- selectX(M = temp$M,
                sample.class = temp$sample.class,
                alteration.class = temp$alteration.class,
                n.cores = 15,
                min.freq = round(0.001*length(temp$sample.class)),
                n.permut = 1000,
                lambda = 0.3,
                tao = 1,
                save.object = FALSE,
                verbose = FALSE,
                estimate_pairwise = FALSE,
                maxFDR = 0.25,
                seed = 42)
label<-paste('../results/','msk_panel_','468','_primary_hotspot_result.rds',sep="")
saveRDS(msk_result,file = label,compress = TRUE)
rm(msk_result)

Total Time: 424.424 sec elapsed