In [1]:
library('SelectSim')
library('tidyverse')
library('tictoc')

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
sessionInfo()

R version 4.4.2 (2024-10-31)
Platform: x86_64-conda-linux-gnu
Running under: AlmaLinux 9.3 (Shamrock Pampas Cat)

Matrix products: default
BLAS/LAPACK: /mnt/ndata/arvind/envs/selectsim_R/lib/libopenblasp-r0.3.29.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Europe/Zurich
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] tictoc_1.2.1      lubridate_1.9.4   forcats_1.0.0     stringr_1.5.1
 [5] dplyr_1.1.4       purrr_1.0.4       readr_2.1.5       tidyr_1.3.1
 [9] tibble_3.2.1      ggplot2_3.5.1     tidyverse_2.0.0   SelectSim_0.0.1.5

loaded via a namespace (and not attached):
 [1] gtable_0.3.6       rstatix_0.7.2      lattice_0.22-6     tzdb_0.5.0
 [5] vctrs_0.6.5        tools_4.4.2        generics_0.1.3     parallel_4.4.2
 [9] pkgconfig_2.0.3    Matrix_1.7-3       ggridges_0.5.6     rngtools_1.5.2
[13] RcppParallel_5.1.9 uuid_1.2-1         lifecycle_1.0.4    compiler_4.4.2
[17] munsell_0.5.1      repr_1.1.7         codetools_0.2-20   carData_3.0-5
[21] htmltools_0.5.8.1  Formula_1.2-5      pillar_1.10.1      car_3.1-3
[25] ggpubr_0.6.0       crayon_1.5.3       doRNG_1.8.6.2      iterators_1.0.14
[29] abind_1.4-5        foreach_1.5.2      tidyselect_1.2.1   digest_0.6.37
[33] stringi_1.8.7      reshape2_1.4.4     fastmap_1.2.0      grid_4.4.2
[37] colorspace_2.1-1   cli_3.6.4          magrittr_2.0.3     base64enc_0.1-3
[41] Rfast_2.1.0        IRdisplay_1.1      broom_1.0.8        withr_3.0.2
[45] scales_1.3.0       backports_1.5.0    IRkernel_1.3.2     RcppZiggurat_0.1.8
[49] timechange_0.3.0   pbdZMQ_0.3-13      ggsignif_0.6.4     hms_1.1.3
[53] evaluate_1.0.3     doParallel_1.0.17  rlang_1.1.5        Rcpp_1.0.14
[57] glue_1.8.0         jsonlite_2.0.0     R6_2.6.1           plyr_1.8.9

# Metadata and Results

In [3]:
all_merged_metadata <- readRDS(file='/mnt/ndata/arvind/co_mutation_project/data/processed/all_merged_data_genie_v15.rds')

In [4]:
all_merged_result<- readRDS(file='/mnt/ndata/arvind/co_mutation_project_revision/catalogue/results/all_merged_results_v15.rds')

In [5]:
msk_gene_list <- readRDS('/mnt/ndata/arvind/co_mutation_project/analysis/catalogue/data/msk_oncokb_gene_run_list.rds')
dfci_gene_list <- readRDS('/mnt/ndata/arvind/co_mutation_project/analysis/catalogue/data/dfci_oncokb_gene_run_list.rds')

# Analysis

In [6]:
head(all_merged_metadata,2)

  sample          class tumor_run oncotree cancer_type              race
1 TCGA-OR-A5J5-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
2 TCGA-OR-A5JB-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
  cohort tumor_run_mapped Tissue        final_tumor_run_mapped
1 TCGA   No mapping       Adrenal Gland ACC
2 TCGA   No mapping       Adrenal Gland ACC

In [7]:
head(all_merged_result,2)

  SFE_1  SFE_2 name          support_1 support_2 freq_1     freq_2   overlap
1 PIK3CA TP53  PIK3CA - TP53 1136      3030      0.12508258 0.333627 357
2 BRAF   TP53  BRAF - TP53    611      3030      0.06727593 0.333627  82
  w_overlap max_overlap ⋯ mean_r_nES nFDR cum_freq nFDR2 type FDR  Cohort Panel
1 317.52971 669         ⋯ -7.492254  0    4166     0     ME   TRUE TCGA   WES
2  53.39755 180         ⋯ -4.691847  0    3641     0     ME   TRUE TCGA   WES
  Tumor_run Mapped_Tumor_run
1 Pan-can   Pan-can
2 Pan-can   Pan-can

# Pan-Can Consistent Hits Strategy
- Extract the significant hits (pair+type) at eFDR <=0.25
    - For MSK-P and DFCI-P found in all gene panel + hits found from specific panels (refer methods for more details)  
- Found in at-least 2 dataset (TCGA, MSK-P, DFCI-P)

In [8]:
all_merged_result_pan_can <- all_merged_result %>% filter(Tumor_run=='Pan-can')

In [9]:
dim(all_merged_result_pan_can)

[1] 445055     26

In [10]:
all_merged_result_pan_can<-all_merged_result_pan_can %>% mutate(id=case_when(SFE_1>SFE_2 ~paste(SFE_2,SFE_1,sep=" - "),
                                                  SFE_1<SFE_2 ~paste(SFE_1,SFE_2,sep=" - "))) %>% mutate(id_type=paste(id,type,sep="_"))

In [11]:
dim(all_merged_result_pan_can)

[1] 445055     28

In [12]:
head(all_merged_result_pan_can,2)

  SFE_1  SFE_2 name          support_1 support_2 freq_1     freq_2   overlap
1 PIK3CA TP53  PIK3CA - TP53 1136      3030      0.12508258 0.333627 357
2 BRAF   TP53  BRAF - TP53    611      3030      0.06727593 0.333627  82
  w_overlap max_overlap ⋯ cum_freq nFDR2 type FDR  Cohort Panel Tumor_run
1 317.52971 669         ⋯ 4166     0     ME   TRUE TCGA   WES   Pan-can
2  53.39755 180         ⋯ 3641     0     ME   TRUE TCGA   WES   Pan-can
  Mapped_Tumor_run id            id_type
1 Pan-can          PIK3CA - TP53 PIK3CA - TP53_ME
2 Pan-can          BRAF - TP53   BRAF - TP53_ME

In [13]:
all<-all_merged_result_pan_can

In [14]:
pan_can_dfci_hits<- unique(all$id_type[ all$Cohort =='DFCI Primary' & all$nFDR2 <=0.25 & all$Tumor_run == 'Pan-can'])
to_remove <- unique(all$id_type[ all$Cohort =='DFCI Primary' & all$nFDR2 > 0.25 & all$Tumor_run == 'Pan-can' & all$Panel=='all'])
pan_can_dfci_hits<- pan_can_dfci_hits[ !(pan_can_dfci_hits %in% to_remove)]

In [15]:
pan_can_msk_hits<- unique(all_merged_result_pan_can$id_type[ all$Cohort =='MSK Primary' & all$nFDR2 <=0.25 & all$Tumor_run == 'Pan-can'])
to_remove <- unique(all_merged_result_pan_can$id_type[ all$Cohort =='MSK Primary' & all$nFDR2 > 0.25 & all$Tumor_run == 'Pan-can' & all$Panel=='all'])
pan_can_msk_hits<- pan_can_msk_hits[ !(pan_can_msk_hits %in% to_remove)]

In [16]:
pan_can_tcga_hits<- unique(all_merged_result_pan_can$id_type[ all$Cohort =='TCGA' & all$nFDR2 <=0.25 & all$Tumor_run == 'Pan-can'])

In [17]:
length(pan_can_tcga_hits)
length(pan_can_dfci_hits)
length(pan_can_msk_hits)

[1] 232

[1] 340

[1] 970

In [18]:
pan_select <- table(c(pan_can_tcga_hits,pan_can_dfci_hits,pan_can_msk_hits))

In [19]:
length(names(pan_select)[pan_select>1])

[1] 329

In [20]:
consistent_hit <- list('fdr_25'=list('tcga'=all_merged_result_pan_can %>% filter(nFDR2<=0.25 & Cohort=='TCGA') %>% filter(id_type %in% pan_can_tcga_hits),
                                    'msk_p'=all_merged_result_pan_can %>% filter(nFDR2<=0.25 & Cohort=='MSK Primary') %>% filter(id_type %in% pan_can_msk_hits),
                                    'dfci_p'=all_merged_result_pan_can %>% filter(nFDR2<=0.25 & Cohort=='DFCI Primary') %>% filter(id_type %in% pan_can_dfci_hits)))

In [21]:
str(consistent_hit)

List of 1
 $ fdr_25:List of 3
  ..$ tcga  :'data.frame':	232 obs. of  28 variables:
  .. ..$ SFE_1           : chr [1:232] "PIK3CA" "BRAF" "ARID1A" "BRAF" ...
  .. ..$ SFE_2           : chr [1:232] "TP53" "TP53" "TP53" "NRAS" ...
  .. ..$ name            : chr [1:232] "PIK3CA - TP53" "BRAF - TP53" "ARID1A - TP53" "BRAF - NRAS" ...
  .. ..$ support_1       : num [1:232] 1136 611 571 611 334 ...
  .. ..$ support_2       : num [1:232] 3030 3030 3030 240 3030 3030 467 3030 635 684 ...
  .. ..$ freq_1          : num [1:232] 0.1251 0.0673 0.0629 0.0673 0.0368 ...
  .. ..$ freq_2          : num [1:232] 0.3336 0.3336 0.3336 0.0264 0.3336 ...
  .. ..$ overlap         : num [1:232] 357 82 147 13 225 158 162 50 201 16 ...
  .. ..$ w_overlap       : num [1:232] 317.53 53.4 115.19 6.35 202.01 ...
  .. ..$ max_overlap     : num [1:232] 669 180 371 191 334 385 193 229 359 125 ...
  .. ..$ freq_overlap    : num [1:232] 0.5336 0.4556 0.3962 0.0681 0.6737 ...
  .. ..$ r_overlap       : num [1:232] 483.7 181 242.6 99.5 199.1 ...
  .. ..$ w_r_overlap     : num [1:232] 392.6 122.4 170.3 54.8 154.2 ...
  .. ..$ wES             : num [1:232] -53.1 -48.8 -39 -34.3 33.8 ...
  .. ..$ wFDR            : num [1:232] 0 0 0 0 0 ...
  .. ..$ nES             : num [1:232] -45.6 -44.1 -34 -31.4 29.4 ...
  .. ..$ mean_r_nES      : num [1:232] -7.49 -4.69 -4.91 -2.85 4.44 ...
  .. ..$ nFDR            : num [1:232] 0 0 0 0 0 ...
  .. ..$ cum_freq        : num [1:232] 4166 3641 3601 851 3364 ...
  .. ..$ nFDR2           : num [1:232] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ type            : chr [1:232] "ME" "ME" "ME" "ME" ...
  .. ..$ FDR             : logi [1:232] TRUE TRUE TRUE TRUE TRUE TRUE ...
  .. ..$ Cohort          : chr [1:232] "TCGA" "TCGA" "TCGA" "TCGA" ...
  .. ..$ Panel           : chr [1:232] "WES" "WES" "WES" "WES" ...
  .. ..$ Tumor_run       : Named chr [1:232] "Pan-can" "Pan-can" "Pan-can" "Pan-can" ...
  .. .. ..- attr(*, "names")= chr [1:232] NA NA NA NA ...
  .. ..$ Mapped_Tumor_run: Named chr [1:232] "Pan-can" "Pan-can" "Pan-can" "Pan-can" ...
  .. .. ..- attr(*, "names")= chr [1:232] "" "" "" "" ...
  .. ..$ id              : chr [1:232] "PIK3CA - TP53" "BRAF - TP53" "ARID1A - TP53" "BRAF - NRAS" ...
  .. ..$ id_type         : chr [1:232] "PIK3CA - TP53_ME" "BRAF - TP53_ME" "ARID1A - TP53_ME" "BRAF - NRAS_ME" ...
  ..$ msk_p :'data.frame':	1808 obs. of  28 variables:
  .. ..$ SFE_1           : chr [1:1808] "PIK3CA" "EGFR" "PTEN" "ARID1A" ...
  .. ..$ SFE_2           : chr [1:1808] "TP53" "KRAS" "TP53" "TP53" ...
  .. ..$ name            : chr [1:1808] "PIK3CA - TP53" "EGFR - KRAS" "PTEN - TP53" "ARID1A - TP53" ...
  .. ..$ support_1       : num [1:1808] 3970 1259 2469 2866 5622 ...
  .. ..$ support_2       : num [1:1808] 12075 5622 12075 12075 12075 ...
  .. ..$ freq_1          : num [1:1808] 0.1427 0.0452 0.0887 0.103 0.202 ...
  .. ..$ freq_2          : num [1:1808] 0.434 0.202 0.434 0.434 0.434 ...
  .. ..$ overlap         : num [1:1808] 1429 36 695 988 2773 ...
  .. ..$ w_overlap       : num [1:1808] 1055.3 15.1 468.9 630.9 2418.5 ...
  .. ..$ max_overlap     : num [1:1808] 3243 1032 1655 2150 5013 ...
  .. ..$ freq_overlap    : num [1:1808] 0.4406 0.0349 0.4199 0.4595 0.5532 ...
  .. ..$ r_overlap       : num [1:1808] 2172 487 1136 1466 3415 ...
  .. ..$ w_r_overlap     : num [1:1808] 1492 296 726 882 2629 ...
  .. ..$ wES             : num [1:1808] -309 -199 -182 -178 -149 ...
  .. ..$ wFDR            : num [1:1808] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ nES             : num [1:1808] -295 -193 -172 -168 -133 ...
  .. ..$ mean_r_nES      : num [1:1808] -13.2 -6.22 -10.02 -10.25 -15.17 ...
  .. ..$ nFDR            : num [1:1808] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ cum_freq        : num [1:1808] 16045 6881 14544 14941 17697 ...
  .. ..$ nFDR2           : num [1:1808] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ type            : chr [1:1808] "ME" "ME" "ME" "ME" ...
  .. ..$ FDR             : logi [1:1808] TRUE TRUE TRUE TRUE TRUE TRUE ...
  .. ..$ Cohort          : chr [1:1808] "MSK Primary" "MSK Primary" "MSK Primary" "MSK Primary" ...
  .. ..$ Panel           : chr [1:1808] "all" "all" "all" "all" ...
  .. ..$ Tumor_run       : Named chr [1:1808] "Pan-can" "Pan-can" "Pan-can" "Pan-can" ...
  .. .. ..- attr(*, "names")= chr [1:1808] NA NA NA NA ...
  .. ..$ Mapped_Tumor_run: Named chr [1:1808] "Pan-can" "Pan-can" "Pan-can" "Pan-can" ...
  .. .. ..- attr(*, "names")= chr [1:1808] "" "" "" "" ...
  .. ..$ id              : chr [1:1808] "PIK3CA - TP53" "EGFR - KRAS" "PTEN - TP53" "ARID1A - TP53" ...
  .. ..$ id_type         : chr [1:1808] "PIK3CA - TP53_ME" "EGFR - KRAS_ME" "PTEN - TP53_ME" "ARID1A - TP53_ME" ...
  ..$ dfci_p:'data.frame':	616 obs. of  28 variables:
  .. ..$ SFE_1           : chr [1:616] "PIK3CA" "EGFR" "APC" "PTEN" ...
  .. ..$ SFE_2           : chr [1:616] "TP53" "KRAS" "TP53" "TP53" ...
  .. ..$ name            : chr [1:616] "PIK3CA - TP53" "EGFR - KRAS" "APC - TP53" "PTEN - TP53" ...
  .. ..$ support_1       : num [1:616] 1968 739 2000 1367 922 ...
  .. ..$ support_2       : num [1:616] 6217 2773 6217 6217 2773 ...
  .. ..$ freq_1          : num [1:616] 0.1343 0.0504 0.1365 0.0933 0.0629 ...
  .. ..$ freq_2          : num [1:616] 0.424 0.189 0.424 0.424 0.189 ...
  .. ..$ overlap         : num [1:616] 738 31 1329 436 65 ...
  .. ..$ w_overlap       : num [1:616] 579.5 19.1 1124.4 336.7 43.7 ...
  .. ..$ max_overlap     : num [1:616] 1631 500 1802 1081 531 ...
  .. ..$ freq_overlap    : num [1:616] 0.452 0.062 0.738 0.403 0.122 ...
  .. ..$ r_overlap       : num [1:616] 1023 234 1266 618 244 ...
  .. ..$ w_r_overlap     : num [1:616] 764 156 989 455 157 ...
  .. ..$ wES             : num [1:616] -130.2 -97.2 96 -83.6 -80.1 ...
  .. ..$ wFDR            : num [1:616] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ nES             : num [1:616] -121.1 -92.4 86.9 -75.3 -75.1 ...
  .. ..$ mean_r_nES      : num [1:616] -9.05 -4.73 9.12 -8.38 -5.04 ...
  .. ..$ nFDR            : num [1:616] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ cum_freq        : num [1:616] 8185 3512 8217 7584 3695 ...
  .. ..$ nFDR2           : num [1:616] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ type            : chr [1:616] "ME" "ME" "CO" "ME" ...
  .. ..$ FDR             : logi [1:616] TRUE TRUE TRUE TRUE TRUE TRUE ...
  .. ..$ Cohort          : chr [1:616] "DFCI Primary" "DFCI Primary" "DFCI Primary" "DFCI Primary" ...
  .. ..$ Panel           : chr [1:616] "all" "all" "all" "all" ...
  .. ..$ Tumor_run       : Named chr [1:616] "Pan-can" "Pan-can" "Pan-can" "Pan-can" ...
  .. .. ..- attr(*, "names")= chr [1:616] NA NA NA NA ...
  .. ..$ Mapped_Tumor_run: Named chr [1:616] "Pan-can" "Pan-can" "Pan-can" "Pan-can" ...
  .. .. ..- attr(*, "names")= chr [1:616] "" "" "" "" ...
  .. ..$ id              : chr [1:616] "PIK3CA - TP53" "EGFR - KRAS" "APC - TP53" "PTEN - TP53" ...
  .. ..$ id_type         : chr [1:616] "PIK3CA - TP53_ME" "EGFR - KRAS_ME" "APC - TP53_CO" "PTEN - TP53_ME" ...

In [22]:
all_merged_result_pan_can_significant <- bind_rows(consistent_hit$fdr_25$tcga,consistent_hit$fdr_25$msk_p,consistent_hit$fdr_25$dfci_p)
rownames(all_merged_result_pan_can_significant)<-c(1:nrow(all_merged_result_pan_can_significant))

In [23]:
head(all_merged_result_pan_can_significant,2)

  SFE_1  SFE_2 name          support_1 support_2 freq_1     freq_2   overlap
1 PIK3CA TP53  PIK3CA - TP53 1136      3030      0.12508258 0.333627 357
2 BRAF   TP53  BRAF - TP53    611      3030      0.06727593 0.333627  82
  w_overlap max_overlap ⋯ cum_freq nFDR2 type FDR  Cohort Panel Tumor_run
1 317.52971 669         ⋯ 4166     0     ME   TRUE TCGA   WES   Pan-can
2  53.39755 180         ⋯ 3641     0     ME   TRUE TCGA   WES   Pan-can
  Mapped_Tumor_run id            id_type
1 Pan-can          PIK3CA - TP53 PIK3CA - TP53_ME
2 Pan-can          BRAF - TP53   BRAF - TP53_ME

In [24]:
pan_can_consistent_motifs<-((all_merged_result_pan_can_significant %>% select(id_type,Cohort) %>% filter(Cohort %in% c('DFCI Primary','MSK Primary','TCGA')) %>% 
distinct() %>% count(id_type) %>% filter(n>=2))$id_type)

In [25]:
pan_can_consistent_motif_v15 <- list('motif'=pan_can_consistent_motifs)

In [26]:
pan_can_consistent_motif_v15$motif_data_df<-all_merged_result_pan_can_significant %>% filter(id_type %in% pan_can_consistent_motifs) %>% filter(Cohort %in% c('DFCI Primary','MSK Primary','TCGA'))

In [27]:
df<-all_merged_result_pan_can_significant %>% filter(Cohort %in% c('DFCI Primary','MSK Primary','TCGA')) %>% 
select(id_type,Cohort,wES) %>% 
group_by(id_type) %>% filter(id_type %in% pan_can_consistent_motifs)

In [28]:
# Group by 'Group' and 'ID' columns and summarize to get maximum effect size for each group and ID combination
df_summary <- df %>%
  group_by(Cohort, id_type) %>%
  summarise(Max_Effect_Size = max(wES))

# Create a wider dataframe
effect_size_df <- pivot_wider(data = df_summary, names_from = Cohort, values_from = Max_Effect_Size) %>% arrange(id_type)

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

In [29]:
effect_size_df

    id_type            DFCI Primary MSK Primary TCGA
1   AKT1 - CTNNB1_CO     7.521202    11.725074          NA
2   AKT1 - GATA3_CO            NA     5.582093    4.514182
3   AKT1 - PIK3CA_ME    -5.240280    -4.278448   -8.762608
4   AKT1 - PTEN_ME      -6.043372   -11.808959   -5.075010
5   AKT1 - TP53_ME     -11.940898    -4.425096   -5.912040
6   APC - ARID1A_ME     -4.680920   -21.108395   -4.857533
7   APC - ARID1B_ME     -6.032562    -5.398042          NA
8   APC - ATM_ME        -8.255533   -10.165160          NA
9   APC - BCOR_ME       -5.654820    -4.179607          NA
10  APC - BRAF_ME       -7.845670    -4.652254  -10.592524
11  APC - CARD11_ME     -4.712585    -5.168903          NA
12  APC - CDH1_ME       -4.842397    -4.562182          NA
13  APC - CTNNB1_ME     -6.761065    -6.585771   -6.680801
14  APC - EGFR_ME       -8.913729    -6.327949          NA
15  APC - IDH1_ME       -6.301023    -5.080643   -3.808566
16  APC - KDM6A_ME      -6.356260    -6.297654          NA
17  APC - KMT2A_ME      -5.056280    -3.879534          NA
18  APC - KMT2D_ME      -5.782209    -3.582614          NA
19  APC - KRAS_CO       71.939087    72.148718          NA
20  APC - NRAS_CO        7.615077     7.582194          NA
21  APC - PBRM1_ME      -5.120314    -5.527849          NA
22  APC - PTEN_ME       -7.952449   -13.622238   -7.344485
23  APC - RB1_ME        -5.010223    -8.759225          NA
24  APC - RBM10_ME      -5.795025    -4.573584          NA
25  APC - RNF43_ME     -27.076425    -6.717703   -5.864578
26  APC - TCF7L2_CO      8.373807    10.340785          NA
27  APC - TP53_CO       95.997893   142.482850          NA
28  APC - ZNRF3_ME      -6.597899    -4.986477          NA
29  ARAF - TP53_ME             NA    -4.646918   -3.461827
30  ARID1A - ARID1B_CO         NA    13.185128    5.212985
⋮   ⋮                  ⋮            ⋮           ⋮
300 PPP2R1A - PTEN_ME          NA    -6.775246   -6.450957
301 PPP2R1A - TP53_CO    5.736899    41.856742    7.041046
302 PTEN - RB1_CO       10.426761           NA    6.996116
303 PTEN - RNF43_CO            NA    10.911633    5.662942
304 PTEN - STAG2_CO     10.713212     4.941100          NA
305 PTEN - STK11_ME     -5.222003    -7.392253          NA
306 PTEN - TP53_ME     -17.016072   -14.176653  -33.914453
307 PTPN11 - TP53_ME    -9.951393    -3.337982   -4.057189
308 RB1 - STAG2_ME      -3.999896    -3.920011          NA
309 RB1 - STK11_ME      -4.465258    -5.319456          NA
310 RB1 - TP53_CO       63.244344    87.346659   20.360496
311 RB1 - TSC1_ME       -4.853671    -3.360382   -3.976225
312 RBM10 - STK11_ME    -4.736487    -6.763298          NA
313 RBM10 - TP53_ME    -20.657060    -7.635814   -5.036358
314 RNF43 - ZNRF3_CO     6.194250     4.405239          NA
315 SETD2 - STK11_ME    -5.349752    -4.857833          NA
316 SETD2 - TP53_ME     -6.002771    -5.217715  -14.886647
317 SF3B1 - TP53_ME     -4.607874    -7.500705   -5.688179
318 SMAD2 - TP53_ME    -10.384924    -2.765515          NA
319 SMARCA4 - STK11_CO   6.374446    11.105388          NA
320 SMARCA4 - TP53_ME          NA    -9.873942   -4.476898
321 SMO - TP53_ME       -5.253811    -4.713187          NA
322 SOX9 - TP53_ME      -7.106291    -5.080929          NA
323 STAG2 - TP53_ME     -2.727190    -7.886098  -12.615822
324 STK11 - TP53_ME     -4.113736    -2.542134  -10.834092
325 TBX3 - TP53_ME             NA    -2.566947   -5.259750
326 TET2 - TP53_ME      -7.887311    -3.977108   -4.598104
327 TP53 - TP53BP1_ME   -4.992190    -7.097434   -4.077892
328 TP53 - TSC1_ME      -9.435760    -3.219821          NA
329 TP53 - VHL_ME       -2.607455    -6.770233  -14.508257

In [30]:
effect_size_df$count <- (df %>% select(id_type,Cohort) %>% ungroup() %>% distinct() %>% count(id_type))$n

In [31]:
head(effect_size_df)

  id_type          DFCI Primary MSK Primary TCGA      count
1 AKT1 - CTNNB1_CO   7.521202    11.725074         NA 2
2 AKT1 - GATA3_CO          NA     5.582093   4.514182 2
3 AKT1 - PIK3CA_ME  -5.240280    -4.278448  -8.762608 3
4 AKT1 - PTEN_ME    -6.043372   -11.808959  -5.075010 3
5 AKT1 - TP53_ME   -11.940898    -4.425096  -5.912040 3
6 APC - ARID1A_ME   -4.680920   -21.108395  -4.857533 3

In [32]:
mean_values <- rowMeans(effect_size_df[, c('DFCI Primary','MSK Primary','TCGA')], na.rm = TRUE)

In [33]:
effect_size_df$mean_ES <- mean_values

In [34]:
head(effect_size_df)

  id_type          DFCI Primary MSK Primary TCGA      count mean_ES
1 AKT1 - CTNNB1_CO   7.521202    11.725074         NA 2       9.623138
2 AKT1 - GATA3_CO          NA     5.582093   4.514182 2       5.048137
3 AKT1 - PIK3CA_ME  -5.240280    -4.278448  -8.762608 3      -6.093779
4 AKT1 - PTEN_ME    -6.043372   -11.808959  -5.075010 3      -7.642447
5 AKT1 - TP53_ME   -11.940898    -4.425096  -5.912040 3      -7.426011
6 APC - ARID1A_ME   -4.680920   -21.108395  -4.857533 3     -10.215616

In [35]:
pan_can_consistent_motif_v15$motif_mean_ES_df<-effect_size_df

In [36]:
str(pan_can_consistent_motif_v15)

List of 3
 $ motif           : chr [1:329] "AKT1 - CTNNB1_CO" "AKT1 - GATA3_CO" "AKT1 - PIK3CA_ME" "AKT1 - PTEN_ME" ...
 $ motif_data_df   :'data.frame':	1521 obs. of  28 variables:
  ..$ SFE_1           : chr [1:1521] "PIK3CA" "BRAF" "ARID1A" "BRAF" ...
  ..$ SFE_2           : chr [1:1521] "TP53" "TP53" "TP53" "NRAS" ...
  ..$ name            : chr [1:1521] "PIK3CA - TP53" "BRAF - TP53" "ARID1A - TP53" "BRAF - NRAS" ...
  ..$ support_1       : num [1:1521] 1136 611 571 611 334 ...
  ..$ support_2       : num [1:1521] 3030 3030 3030 240 3030 3030 467 3030 635 684 ...
  ..$ freq_1          : num [1:1521] 0.1251 0.0673 0.0629 0.0673 0.0368 ...
  ..$ freq_2          : num [1:1521] 0.3336 0.3336 0.3336 0.0264 0.3336 ...
  ..$ overlap         : num [1:1521] 357 82 147 13 225 158 162 50 201 16 ...
  ..$ w_overlap       : num [1:1521] 317.53 53.4 115.19 6.35 202.01 ...
  ..$ max_overlap     : num [1:1521] 669 180 371 191 334 385 193 229 359 125 ...
  ..$ freq_overlap    : num [1:1521] 0.5336 0.4556 0.3962 0.0681 0.6737 ...
  ..$ r_overlap       : num [1:1521] 483.7 181 242.6 99.5 199.1 ...
  ..$ w_r_overlap     : num [1:1521] 392.6 122.4 170.3 54.8 154.2 ...
  ..$ wES             : num [1:1521] -53.1 -48.8 -39 -34.3 33.8 ...
  ..$ wFDR            : num [1:1521] 0 0 0 0 0 ...
  ..$ nES             : num [1:1521] -45.6 -44.1 -34 -31.4 29.4 ...
  ..$ mean_r_nES      : num [1:1521] -7.49 -4.69 -4.91 -2.85 4.44 ...
  ..$ nFDR            : num [1:1521] 0 0 0 0 0 ...
  ..$ cum_freq        : num [1:1521] 4166 3641 3601 851 3364 ...
  ..$ nFDR2           : num [1:1521] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ type            : chr [1:1521] "ME" "ME" "ME" "ME" ...
  ..$ FDR             : logi [1:1521] TRUE TRUE TRUE TRUE TRUE TRUE ...
  ..$ Cohort          : chr [1:1521] "TCGA" "TCGA" "TCGA" "TCGA" ...
  ..$ Panel           : chr [1:1521] "WES" "WES" "WES" "WES" ...
  ..$ Tumor_run       : Named chr [1:1521] "Pan-can" "Pan-can" "Pan-can" "Pan-can" ...
  .. ..- attr(*, "names")= chr [1:1521] NA NA NA NA ...
  ..$ Mapped_Tumor_run: Named chr [1:1521] "Pan-can" "Pan-can" "Pan-can" "Pan-can" ...
  .. ..- attr(*, "names")= chr [1:1521] "" "" "" "" ...
  ..$ id              : chr [1:1521] "PIK3CA - TP53" "BRAF - TP53" "ARID1A - TP53" "BRAF - NRAS" ...
  ..$ id_type         : chr [1:1521] "PIK3CA - TP53_ME" "BRAF - TP53_ME" "ARID1A - TP53_ME" "BRAF - NRAS_ME" ...
 $ motif_mean_ES_df: tibble [329 × 6] (S3: tbl_df/tbl/data.frame)
  ..$ id_type     : chr [1:329] "AKT1 - CTNNB1_CO" "AKT1 - GATA3_CO" "AKT1 - PIK3CA_ME" "AKT1 - PTEN_ME" ...
  ..$ DFCI Primary: num [1:329] 7.52 NA -5.24 -6.04 -11.94 ...
  ..$ MSK Primary : num [1:329] 11.73 5.58 -4.28 -11.81 -4.43 ...
  ..$ TCGA        : num [1:329] NA 4.51 -8.76 -5.08 -5.91 ...
  ..$ count       : int [1:329] 2 2 3 3 3 3 2 2 2 3 ...
  ..$ mean_ES     : num [1:329] 9.62 5.05 -6.09 -7.64 -7.43 ...

In [37]:
saveRDS(pan_can_consistent_motif_v15,file='../results/pan_can_consistent_motif_v15_fdr_25_update.rds')

# Tumor Classes Consistent Hits Strategy
- Extract the significant hits (pair+type) at eFDR <=0.25
    - For MSK-P and DFCI-P found in all gene panel + hits found from specific panels (refer methods for more details)  
- Mapping of TCGA tumor runs to MSK and DFCI tumor runs
- Common Tumor groups across primary cohort
- Found in at-least 2 dataset (TCGA, MSK-P, DFCI-P)

In [38]:
all_merged_result_tumor_can <- all_merged_result %>% filter(Tumor_run!='Pan-can') %>% mutate(id=case_when(SFE_1>SFE_2 ~paste(SFE_2,SFE_1,sep=" - "),
                                                  SFE_1<SFE_2 ~paste(SFE_1,SFE_2,sep=" - "))) %>% mutate(id_type=paste(id,type,sep="_"))

In [39]:
tumor_mapped <- (all_merged_metadata %>% filter(cohort=='TCGA') %>% select(tumor_run,tumor_run_mapped) %>% distinct())$tumor_run_mapped
names(tumor_mapped)<-(all_merged_metadata %>% filter(cohort=='TCGA') %>% select(tumor_run,tumor_run_mapped) %>% distinct())$tumor_run

In [41]:
temp<-unlist((all_merged_metadata %>% filter(cohort=='TCGA') %>% select(tumor_run,tumor_run_mapped) %>% distinct())$tumor_run_mapped)

In [42]:
cleaned_tumor_groups <- tolower(gsub("[[:space:]/-]", "_", temp))

In [43]:
tumor_mapped <- cleaned_tumor_groups
names(tumor_mapped)<-(all_merged_metadata %>% filter(cohort=='TCGA') %>% select(tumor_run,tumor_run_mapped) %>% distinct())$tumor_run

In [44]:
tumor_mapped

                         ACC                         BLCA
                "no_mapping"             "bladder_cancer"
                      Breast                         CESC
             "breast_cancer"            "cervical_cancer"
                        CHOL                          CRC
      "billary_tract_cancer"          "colorectal_cancer"
                    Lymphoma                         ESCA
   "mature_b_cell_neoplasms"     "esophagogastric_cancer"
                          GB                         HNSC
                    "glioma"       "head_and_neck_cancer"
                      NCCRCC                        CCRCC
      "renal_cell_carcinoma"       "renal_cell_carcinoma"
                         AML                         DIFG
                  "leukemia"                     "glioma"
                         HCC                         Lung
              "liver_cancer" "non_small_cell_lung_cancer"
                      PLMESO                          SOC
              "mesothelioma"             "ovarian_cancer"
                        PAAD                         PCPG
         "pancreatic_cancer"                 "no_mapping"
                   Prostrate                         SARC
           "prostate_cancer"        "soft_tissue_sarcoma"
                         MEL                         STAD
                  "melanoma"     "esophagogastric_cancer"
                        TGCT                         THPA
           "germ_cell_tumor"             "thyroid_cancer"
                        THYM                         UCEC
                "no_mapping"         "endometrial_cancer"
                          UM
                  "melanoma"

In [45]:
all_merged_result_tumor_can <- all_merged_result %>% filter(Tumor_run!='Pan-can') %>% mutate(id=case_when(SFE_1>SFE_2 ~paste(SFE_2,SFE_1,sep=" - "),
                                                  SFE_1<SFE_2 ~paste(SFE_1,SFE_2,sep=" - "))) %>% mutate(id_type=paste(id,type,sep="_"))

In [46]:
head(all_merged_result_tumor_can)

  SFE_1  SFE_2  name            support_1 support_2 freq_1     freq_2
1 NF1    TP53   NF1 - TP53      4         15        0.05263158 0.19736842
2 BCORL1 U2AF1  BCORL1 - U2AF1  1          1        0.01315789 0.01315789
3 PIK3CA ROS1   PIK3CA - ROS1   1          1        0.01315789 0.01315789
4 ARID3A ARID4A ARID3A - ARID4A 1          1        0.01315789 0.01315789
5 ATM    MEN1   ATM - MEN1      2          6        0.02631579 0.07894737
6 DICER1 RB1    DICER1 - RB1    1          2        0.01315789 0.02631579
  overlap w_overlap max_overlap ⋯ cum_freq nFDR2      type FDR   Cohort Panel
1 4       1.7289765 4           ⋯ 19       0.09778813 CO    TRUE TCGA   WES
2 1       0.7692308 1           ⋯  2       1.00000000 CO   FALSE TCGA   WES
3 1       0.7692308 1           ⋯  2       1.00000000 CO   FALSE TCGA   WES
4 1       0.7692308 1           ⋯  2       1.00000000 CO   FALSE TCGA   WES
5 1       1.0000000 2           ⋯  8       0.80558789 CO   FALSE TCGA   WES
6 1       0.7692308 1           ⋯  3       1.00000000 CO   FALSE TCGA   WES
  Tumor_run Mapped_Tumor_run id              id_type
1 ACC       no_mapping       NF1 - TP53      NF1 - TP53_CO
2 ACC       no_mapping       BCORL1 - U2AF1  BCORL1 - U2AF1_CO
3 ACC       no_mapping       PIK3CA - ROS1   PIK3CA - ROS1_CO
4 ACC       no_mapping       ARID3A - ARID4A ARID3A - ARID4A_CO
5 ACC       no_mapping       ATM - MEN1      ATM - MEN1_CO
6 ACC       no_mapping       DICER1 - RB1    DICER1 - RB1_CO

In [47]:
tcga_tumor_runs <- unique((all_merged_result_tumor_can %>% filter(Cohort %in% c('TCGA')))$Mapped_Tumor_run)
msk_tumor_runs <- unique((all_merged_result_tumor_can %>% filter(Cohort %in% c('MSK Primary')))$Mapped_Tumor_run)
dfci_tumor_runs <- unique((all_merged_result_tumor_can %>% filter(Cohort %in% c('DFCI Primary')))$Mapped_Tumor_run)

In [48]:
all_primary_tumor_runs <- (Reduce(intersect,list(tcga_tumor_runs,msk_tumor_runs,dfci_tumor_runs)))

In [49]:
length(all_primary_tumor_runs)

[1] 19

In [50]:
all_primary_tumor_runs

 [1] "bladder_cancer"             "breast_cancer"
 [3] "billary_tract_cancer"       "colorectal_cancer"
 [5] "mature_b_cell_neoplasms"    "esophagogastric_cancer"
 [7] "glioma"                     "head_and_neck_cancer"
 [9] "renal_cell_carcinoma"       "leukemia"
[11] "non_small_cell_lung_cancer" "mesothelioma"
[13] "ovarian_cancer"             "pancreatic_cancer"
[15] "prostate_cancer"            "soft_tissue_sarcoma"
[17] "melanoma"                   "thyroid_cancer"
[19] "endometrial_cancer"

In [51]:
all_merged_result_tumor_can <- all_merged_result_tumor_can %>% filter(Mapped_Tumor_run %in% all_primary_tumor_runs)

In [52]:
tcga_all_ids <- (all_merged_result_tumor_can %>% filter(Cohort=='TCGA' & nFDR2<=0.25 ) %>% select(id_type) %>% distinct())$id_type

In [53]:
not_in_all<-setdiff((unique(Reduce(union,msk_gene_list[2:6]))),msk_gene_list$all)
msk_all_significant_ids_1<-(all_merged_result_tumor_can %>% filter(Cohort=='MSK Primary' & nFDR2<=0.25) %>% filter(Panel=='all') %>% select(id_type) %>% distinct())$id_type
msk_all_significant_ids_2<-(all_merged_result_tumor_can %>% filter(Cohort=='MSK Primary' & nFDR2<=0.25) %>% filter(SFE_1 %in% not_in_all | SFE_2 %in% not_in_all) %>% select(id_type) %>% distinct())$id_type
msk_all_significant<-unique(c(msk_all_significant_ids_1,msk_all_significant_ids_2))

In [54]:
not_in_all<-setdiff(unique(c(dfci_gene_list$p_1,dfci_gene_list$p_2,dfci_gene_list$p_3)),dfci_gene_list$all)
dfci_all_significant_ids_1<-(all_merged_result_tumor_can %>% filter(Cohort=='DFCI Primary' & nFDR2<=0.25) %>% filter(Panel=='all' ) %>% select(id_type) %>% distinct())$id_type
dfci_all_significant_ids_2<-(all_merged_result_tumor_can %>% filter(Cohort=='DFCI Primary' & nFDR2<=0.25)  %>% filter(SFE_1 %in% not_in_all | SFE_2 %in% not_in_all) %>% select(id_type) %>% distinct())$id_type
dfci_all_significant<-unique(c(dfci_all_significant_ids_1,dfci_all_significant_ids_2))

In [55]:
length(tcga_all_ids)
length(msk_all_significant)
length(dfci_all_significant)

[1] 478

[1] 1382

[1] 502

In [56]:
all_significant_ids <- list('TCGA'=tcga_all_ids,
                            'MSK_P'=msk_all_significant,
                            'DFCI_P'=dfci_all_significant)

In [57]:
tumor_consistent_hit <- list('fdr_25'=list('tcga'=all_merged_result_tumor_can %>% filter(nFDR2<=0.25 & Mapped_Tumor_run!='no_mapping'&Cohort=='TCGA') %>% filter(id_type %in% all_significant_ids$TCGA),
                                    'msk_p'=all_merged_result_tumor_can %>% filter(nFDR2<=0.25 & Mapped_Tumor_run!='no_mapping'&Cohort=='MSK Primary') %>% filter(id_type %in% all_significant_ids$MSK_P),
                                    'dfci_p'=all_merged_result_tumor_can %>% filter(nFDR2<=0.25 &Mapped_Tumor_run!='no_mapping'& Cohort=='DFCI Primary') %>% filter(id_type %in% all_significant_ids$DFCI_P)))

In [58]:
all_merged_result_tumor_can_significant <- bind_rows(tumor_consistent_hit$fdr_25$tcga,tumor_consistent_hit$fdr_25$msk_p,tumor_consistent_hit$fdr_25$dfci_p)
rownames(all_merged_result_tumor_can_significant)<-c(1:nrow(all_merged_result_tumor_can_significant))

In [59]:
head(all_merged_result_tumor_can_significant,2)

  SFE_1 SFE_2 name         support_1 support_2 freq_1     freq_2    overlap
1 RB1   TP53  RB1 - TP53   70        175       0.17587940 0.4396985 52
2 FGFR3 TP53  FGFR3 - TP53 38        175       0.09547739 0.4396985  6
  w_overlap max_overlap ⋯ cum_freq nFDR2 type FDR  Cohort Panel Tumor_run
1 41.818108 70          ⋯ 245      0     CO   TRUE TCGA   WES   BLCA
2  4.387238 38          ⋯ 213      0     ME   TRUE TCGA   WES   BLCA
  Mapped_Tumor_run id           id_type
1 bladder_cancer   RB1 - TP53   RB1 - TP53_CO
2 bladder_cancer   FGFR3 - TP53 FGFR3 - TP53_ME

In [60]:
primary_consider_tumor_runs <- unique((all_merged_result_tumor_can_significant %>% filter(Cohort %in% c('DFCI Primary','MSK Primary','TCGA')))$Mapped_Tumor_run)

In [61]:
length(primary_consider_tumor_runs)

[1] 19

In [62]:
tcga_tumor_runs <- unique((all_merged_result_tumor_can_significant %>% filter(Cohort %in% c('TCGA')))$Mapped_Tumor_run)
msk_tumor_runs <- unique((all_merged_result_tumor_can_significant %>% filter(Cohort %in% c('MSK Primary')))$Mapped_Tumor_run)
dfci_tumor_runs <- unique((all_merged_result_tumor_can_significant %>% filter(Cohort %in% c('DFCI Primary')))$Mapped_Tumor_run)

In [63]:
all_primary_tumor_runs <- (Reduce(intersect,list(tcga_tumor_runs,msk_tumor_runs,dfci_tumor_runs)))

In [64]:
length(all_primary_tumor_runs)

[1] 18

In [65]:
all_primary_tumor_runs

 [1] "bladder_cancer"             "breast_cancer"
 [3] "billary_tract_cancer"       "colorectal_cancer"
 [5] "esophagogastric_cancer"     "glioma"
 [7] "head_and_neck_cancer"       "renal_cell_carcinoma"
 [9] "leukemia"                   "non_small_cell_lung_cancer"
[11] "mesothelioma"               "ovarian_cancer"
[13] "pancreatic_cancer"          "prostate_cancer"
[15] "soft_tissue_sarcoma"        "melanoma"
[17] "thyroid_cancer"             "endometrial_cancer"

In [66]:
tumor_can_consistent_motif <- list()
all_motifs <- c()

In [67]:
for(tumor_run in all_primary_tumor_runs){
    cat('--Running--',tumor_run,"\n")
    cancer_df <- all_merged_result_tumor_can_significant %>% filter(Cohort %in% c('DFCI Primary','MSK Primary','TCGA')) %>% 
                 filter(Mapped_Tumor_run==tumor_run)
    cancer_all_motif_list <- (cancer_df%>% select(id_type,Cohort)%>% distinct() %>% count(id_type) %>% filter(n>=2))$id_type
    cancer_all <-     (cancer_df%>% select(id_type,Cohort)%>% distinct() %>% count(id_type) %>% filter(n>=3))$id_type
    cancer_atleast_two <-     (cancer_df%>% select(id_type,Cohort)%>% distinct() %>% count(id_type) %>% filter(n==2))$id_type
    if(length(cancer_all_motif_list)>=1){
        df<-cancer_df %>% select(id_type,Cohort,wES) %>% group_by(id_type) %>% filter(id_type %in% cancer_all_motif_list)
        df_summary <- df %>% group_by(Cohort, id_type) %>% summarise(Max_Effect_Size = max(wES))
        effect_size_df <- pivot_wider(data = df_summary, names_from = Cohort, values_from = Max_Effect_Size) %>% arrange(id_type)
        effect_size_df$count <- (df %>% select(id_type,Cohort) %>% ungroup() %>% distinct() %>% count(id_type))$n
        intersect_cols <- intersect(c('DFCI Primary','MSK Primary','TCGA'),colnames(effect_size_df))
        mean_values <- rowMeans(effect_size_df[, intersect_cols], na.rm = TRUE)
        effect_size_df$mean_ES <- mean_values
        tumor_can_consistent_motif[[tumor_run]]<-list('all_motif'=cancer_all_motif_list,
                                                      'motif_list'=list('all'=cancer_all,'atleast_two'=cancer_atleast_two),
                                                      'motif_data_df'=cancer_df,
                                                      'motif_mean_ES_df'=effect_size_df)
        all_motifs<-unique(c(all_motifs,cancer_all_motif_list))
    }
    cat('--Running Done--',tumor_run,"\n")
}

--Running-- bladder_cancer

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- bladder_cancer
--Running-- breast_cancer

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- breast_cancer
--Running-- billary_tract_cancer

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- billary_tract_cancer
--Running-- colorectal_cancer

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- colorectal_cancer
--Running-- esophagogastric_cancer

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- esophagogastric_cancer
--Running-- glioma

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- glioma
--Running-- head_and_neck_cancer

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- head_and_neck_cancer
--Running-- renal_cell_carcinoma

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- renal_cell_carcinoma
--Running-- leukemia

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- leukemia
--Running-- non_small_cell_lung_cancer

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- non_small_cell_lung_cancer
--Running-- mesothelioma

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- mesothelioma
--Running-- ovarian_cancer

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- ovarian_cancer
--Running-- pancreatic_cancer

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- pancreatic_cancer
--Running-- prostate_cancer

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- prostate_cancer
--Running-- soft_tissue_sarcoma
--Running Done-- soft_tissue_sarcoma
--Running-- melanoma

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- melanoma
--Running-- thyroid_cancer

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- thyroid_cancer
--Running-- endometrial_cancer

`summarise()` has grouped output by 'Cohort'. You can override using the `.groups` argument.

--Running Done-- endometrial_cancer

In [68]:
length(unique(all_motifs))

[1] 439

In [69]:
str(tumor_can_consistent_motif,max.level = 2)

List of 17
 $ bladder_cancer            :List of 4
  ..$ all_motif       : chr [1:67] "AKT1 - TP53_ME" "ARID1A - CDKN2A_ME" "ARID1A - CTNNB1_CO" "ARID1A - FAT1_ME" ...
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	517 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [67 × 6] (S3: tbl_df/tbl/data.frame)
 $ breast_cancer             :List of 4
  ..$ all_motif       : chr [1:44] "AKT1 - GATA3_CO" "AKT1 - PIK3CA_ME" "AKT1 - TP53_ME" "ARID1A - TP53_ME" ...
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	322 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [44 × 6] (S3: tbl_df/tbl/data.frame)
 $ billary_tract_cancer      :List of 4
  ..$ all_motif       : chr [1:6] "ARID1A - KRAS_ME" "ARID1A - TP53_ME" "BAP1 - TP53_ME" "IDH1 - KRAS_ME" ...
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	88 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [6 × 5] (S3: tbl_df/tbl/data.frame)
 $ colorectal_cancer         :List of 4
  ..$ all_motif       : chr [1:131] "AKT1 - TP53_ME" "AMER1 - KRAS_CO" "APC - ARAF_ME" "APC - ARHGAP35_ME" ...
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	1050 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [131 × 6] (S3: tbl_df/tbl/data.frame)
 $ esophagogastric_cancer    :List of 4
  ..$ all_motif       : chr [1:30] "APC - ARID1A_ME" "APC - KRAS_CO" "ARAF - TP53_ME" "ARID1A - PIK3CA_CO" ...
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	228 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [30 × 6] (S3: tbl_df/tbl/data.frame)
 $ glioma                    :List of 4
  ..$ all_motif       : chr [1:49] "ARID1A - TP53_ME" "ATM - PTEN_ME" "ATRX - CIC_ME" "ATRX - EGFR_ME" ...
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	330 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [49 × 6] (S3: tbl_df/tbl/data.frame)
 $ head_and_neck_cancer      :List of 4
  ..$ all_motif       : chr [1:7] "ARID1A - TP53_ME" "CASP8 - CDKN2A_CO" "CDKN2A - TP53_CO" "EP300 - TP53_ME" ...
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	66 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [7 × 6] (S3: tbl_df/tbl/data.frame)
 $ renal_cell_carcinoma      :List of 4
  ..$ all_motif       : chr [1:3] "BAP1 - PBRM1_ME" "PBRM1 - SETD2_CO" "PBRM1 - VHL_CO"
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	37 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [3 × 6] (S3: tbl_df/tbl/data.frame)
 $ leukemia                  :List of 4
  ..$ all_motif       : chr [1:7] "ASXL1 - SRSF2_CO" "DNMT3A - IDH1_CO" "DNMT3A - NPM1_CO" "FLT3 - NPM1_CO" ...
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	46 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [7 × 6] (S3: tbl_df/tbl/data.frame)
 $ non_small_cell_lung_cancer:List of 4
  ..$ all_motif       : chr [1:73] "ARID1A - EGFR_ME" "ARID1A - STK11_ME" "ATM - EGFR_ME" "ATM - KRAS_CO" ...
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	626 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [73 × 6] (S3: tbl_df/tbl/data.frame)
 $ mesothelioma              :List of 4
  ..$ all_motif       : chr "BAP1 - TP53_ME"
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	8 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [1 × 5] (S3: tbl_df/tbl/data.frame)
 $ ovarian_cancer            :List of 4
  ..$ all_motif       : chr [1:3] "ARID1A - PIK3CA_CO" "ARID1A - TP53_ME" "PIK3CA - TP53_ME"
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	55 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [3 × 5] (S3: tbl_df/tbl/data.frame)
 $ pancreatic_cancer         :List of 4
  ..$ all_motif       : chr [1:15] "ATM - TP53_ME" "BRAF - KRAS_ME" "BRCA2 - TP53_ME" "CDKN2A - KRAS_CO" ...
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	189 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [15 × 6] (S3: tbl_df/tbl/data.frame)
 $ prostate_cancer           :List of 4
  ..$ all_motif       : chr [1:3] "ATM - TP53_ME" "BRCA2 - TP53_ME" "KMT2D - TP53_ME"
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	85 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [3 × 5] (S3: tbl_df/tbl/data.frame)
 $ melanoma                  :List of 4
  ..$ all_motif       : chr [1:15] "ARID1A - BRAF_ME" "ARID1A - NRAS_ME" "BAP1 - GNAQ_CO" "BRAF - CBL_ME" ...
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	162 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [15 × 6] (S3: tbl_df/tbl/data.frame)
 $ thyroid_cancer            :List of 4
  ..$ all_motif       : chr [1:3] "BRAF - HRAS_ME" "BRAF - KRAS_ME" "BRAF - NRAS_ME"
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	43 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [3 × 6] (S3: tbl_df/tbl/data.frame)
 $ endometrial_cancer        :List of 4
  ..$ all_motif       : chr [1:106] "AKT1 - ARID1A_ME" "AKT1 - CTNNB1_CO" "AKT1 - PIK3CA_ME" "AKT1 - PIK3R1_ME" ...
  ..$ motif_list      :List of 2
  ..$ motif_data_df   :'data.frame':	1112 obs. of  28 variables:
  ..$ motif_mean_ES_df: tibble [106 × 6] (S3: tbl_df/tbl/data.frame)

In [70]:
tumor_can_consistent_motif_v15<- list('tumor_types'=names(tumor_can_consistent_motif),
                                       'all_motif'=all_motifs,
                                       'tumor_run_lists'=tumor_can_consistent_motif)

In [71]:
str(tumor_can_consistent_motif_v15,max.level = 3)

List of 3
 $ tumor_types    : chr [1:17] "bladder_cancer" "breast_cancer" "billary_tract_cancer" "colorectal_cancer" ...
 $ all_motif      : chr [1:439] "AKT1 - TP53_ME" "ARID1A - CDKN2A_ME" "ARID1A - CTNNB1_CO" "ARID1A - FAT1_ME" ...
 $ tumor_run_lists:List of 17
  ..$ bladder_cancer            :List of 4
  .. ..$ all_motif       : chr [1:67] "AKT1 - TP53_ME" "ARID1A - CDKN2A_ME" "ARID1A - CTNNB1_CO" "ARID1A - FAT1_ME" ...
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	517 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [67 × 6] (S3: tbl_df/tbl/data.frame)
  ..$ breast_cancer             :List of 4
  .. ..$ all_motif       : chr [1:44] "AKT1 - GATA3_CO" "AKT1 - PIK3CA_ME" "AKT1 - TP53_ME" "ARID1A - TP53_ME" ...
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	322 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [44 × 6] (S3: tbl_df/tbl/data.frame)
  ..$ billary_tract_cancer      :List of 4
  .. ..$ all_motif       : chr [1:6] "ARID1A - KRAS_ME" "ARID1A - TP53_ME" "BAP1 - TP53_ME" "IDH1 - KRAS_ME" ...
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	88 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [6 × 5] (S3: tbl_df/tbl/data.frame)
  ..$ colorectal_cancer         :List of 4
  .. ..$ all_motif       : chr [1:131] "AKT1 - TP53_ME" "AMER1 - KRAS_CO" "APC - ARAF_ME" "APC - ARHGAP35_ME" ...
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	1050 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [131 × 6] (S3: tbl_df/tbl/data.frame)
  ..$ esophagogastric_cancer    :List of 4
  .. ..$ all_motif       : chr [1:30] "APC - ARID1A_ME" "APC - KRAS_CO" "ARAF - TP53_ME" "ARID1A - PIK3CA_CO" ...
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	228 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [30 × 6] (S3: tbl_df/tbl/data.frame)
  ..$ glioma                    :List of 4
  .. ..$ all_motif       : chr [1:49] "ARID1A - TP53_ME" "ATM - PTEN_ME" "ATRX - CIC_ME" "ATRX - EGFR_ME" ...
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	330 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [49 × 6] (S3: tbl_df/tbl/data.frame)
  ..$ head_and_neck_cancer      :List of 4
  .. ..$ all_motif       : chr [1:7] "ARID1A - TP53_ME" "CASP8 - CDKN2A_CO" "CDKN2A - TP53_CO" "EP300 - TP53_ME" ...
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	66 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [7 × 6] (S3: tbl_df/tbl/data.frame)
  ..$ renal_cell_carcinoma      :List of 4
  .. ..$ all_motif       : chr [1:3] "BAP1 - PBRM1_ME" "PBRM1 - SETD2_CO" "PBRM1 - VHL_CO"
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	37 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [3 × 6] (S3: tbl_df/tbl/data.frame)
  ..$ leukemia                  :List of 4
  .. ..$ all_motif       : chr [1:7] "ASXL1 - SRSF2_CO" "DNMT3A - IDH1_CO" "DNMT3A - NPM1_CO" "FLT3 - NPM1_CO" ...
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	46 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [7 × 6] (S3: tbl_df/tbl/data.frame)
  ..$ non_small_cell_lung_cancer:List of 4
  .. ..$ all_motif       : chr [1:73] "ARID1A - EGFR_ME" "ARID1A - STK11_ME" "ATM - EGFR_ME" "ATM - KRAS_CO" ...
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	626 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [73 × 6] (S3: tbl_df/tbl/data.frame)
  ..$ mesothelioma              :List of 4
  .. ..$ all_motif       : chr "BAP1 - TP53_ME"
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	8 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [1 × 5] (S3: tbl_df/tbl/data.frame)
  ..$ ovarian_cancer            :List of 4
  .. ..$ all_motif       : chr [1:3] "ARID1A - PIK3CA_CO" "ARID1A - TP53_ME" "PIK3CA - TP53_ME"
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	55 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [3 × 5] (S3: tbl_df/tbl/data.frame)
  ..$ pancreatic_cancer         :List of 4
  .. ..$ all_motif       : chr [1:15] "ATM - TP53_ME" "BRAF - KRAS_ME" "BRCA2 - TP53_ME" "CDKN2A - KRAS_CO" ...
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	189 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [15 × 6] (S3: tbl_df/tbl/data.frame)
  ..$ prostate_cancer           :List of 4
  .. ..$ all_motif       : chr [1:3] "ATM - TP53_ME" "BRCA2 - TP53_ME" "KMT2D - TP53_ME"
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	85 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [3 × 5] (S3: tbl_df/tbl/data.frame)
  ..$ melanoma                  :List of 4
  .. ..$ all_motif       : chr [1:15] "ARID1A - BRAF_ME" "ARID1A - NRAS_ME" "BAP1 - GNAQ_CO" "BRAF - CBL_ME" ...
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	162 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [15 × 6] (S3: tbl_df/tbl/data.frame)
  ..$ thyroid_cancer            :List of 4
  .. ..$ all_motif       : chr [1:3] "BRAF - HRAS_ME" "BRAF - KRAS_ME" "BRAF - NRAS_ME"
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	43 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [3 × 6] (S3: tbl_df/tbl/data.frame)
  ..$ endometrial_cancer        :List of 4
  .. ..$ all_motif       : chr [1:106] "AKT1 - ARID1A_ME" "AKT1 - CTNNB1_CO" "AKT1 - PIK3CA_ME" "AKT1 - PIK3R1_ME" ...
  .. ..$ motif_list      :List of 2
  .. ..$ motif_data_df   :'data.frame':	1112 obs. of  28 variables:
  .. ..$ motif_mean_ES_df: tibble [106 × 6] (S3: tbl_df/tbl/data.frame)

In [72]:
saveRDS(tumor_can_consistent_motif_v15,file='../results/tumor_can_consistent_motif_v15_fdr_25_update.rds')