In [1]:
library('SelectSim')
library('tidyverse')

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
sessionInfo()

R version 4.4.2 (2024-10-31)
Platform: x86_64-conda-linux-gnu
Running under: AlmaLinux 9.3 (Shamrock Pampas Cat)

Matrix products: default
BLAS/LAPACK: /mnt/ndata/arvind/envs/selectsim_R/lib/libopenblasp-r0.3.29.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Europe/Zurich
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] lubridate_1.9.4   forcats_1.0.0     stringr_1.5.1     dplyr_1.1.4
 [5] purrr_1.0.4       readr_2.1.5       tidyr_1.3.1       tibble_3.2.1
 [9] ggplot2_3.5.1     tidyverse_2.0.0   SelectSim_0.0.1.5

loaded via a namespace (and not attached):
 [1] gtable_0.3.6       rstatix_0.7.2      lattice_0.22-6     tzdb_0.5.0
 [5] vctrs_0.6.5        tools_4.4.2        generics_0.1.3     parallel_4.4.2
 [9] pkgconfig_2.0.3    Matrix_1.7-3       ggridges_0.5.6     rngtools_1.5.2
[13] RcppParallel_5.1.9 uuid_1.2-1         lifecycle_1.0.4    compiler_4.4.2
[17] tictoc_1.2.1       munsell_0.5.1      repr_1.1.7         codetools_0.2-20
[21] carData_3.0-5      htmltools_0.5.8.1  Formula_1.2-5      pillar_1.10.1
[25] car_3.1-3          ggpubr_0.6.0       crayon_1.5.3       doRNG_1.8.6.2
[29] iterators_1.0.14   abind_1.4-5        foreach_1.5.2      tidyselect_1.2.1
[33] digest_0.6.37      stringi_1.8.7      reshape2_1.4.4     fastmap_1.2.0
[37] grid_4.4.2         colorspace_2.1-1   cli_3.6.4          magrittr_2.0.3
[41] base64enc_0.1-3    Rfast_2.1.0        IRdisplay_1.1      broom_1.0.8
[45] withr_3.0.2        scales_1.3.0       backports_1.5.0    IRkernel_1.3.2
[49] RcppZiggurat_0.1.8 timechange_0.3.0   pbdZMQ_0.3-13      ggsignif_0.6.4
[53] hms_1.1.3          evaluate_1.0.3     doParallel_1.0.17  rlang_1.1.5
[57] Rcpp_1.0.14        glue_1.8.0         jsonlite_2.0.0     R6_2.6.1
[61] plyr_1.8.9

# Metadata

In [3]:
all_merged_metdata <- readRDS(file='/mnt/ndata/arvind/co_mutation_project/data/processed/all_merged_data_genie_v15.rds')

In [4]:
head(all_merged_metdata,2)

  sample          class tumor_run oncotree cancer_type              race
1 TCGA-OR-A5J5-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
2 TCGA-OR-A5JB-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
  cohort tumor_run_mapped Tissue        final_tumor_run_mapped
1 TCGA   No mapping       Adrenal Gland ACC
2 TCGA   No mapping       Adrenal Gland ACC

## TCGA Pan-Cancer

In [5]:
run_data<-readRDS('/mnt/ndata/arvind/co_mutation_project/data/processed/gams/pan_can_tcga_run_data.rds')

In [6]:
str(run_data)

List of 3
 $ M               :List of 2
  ..$ M  :List of 2
  .. ..$ missense  : num [1:396, 1:9082] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:396] "AKT1" "ALK" "APC" "AR" ...
  .. .. .. ..$ : chr [1:9082] "TCGA-02-0047-01" "TCGA-02-0055-01" "TCGA-AB-2805-03" "TCGA-AB-2806-03" ...
  .. ..$ truncating: num [1:396, 1:9082] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:396] "AKT1" "ALK" "APC" "AR" ...
  .. .. .. ..$ : chr [1:9082] "TCGA-02-0047-01" "TCGA-02-0055-01" "TCGA-AB-2805-03" "TCGA-AB-2806-03" ...
  ..$ tmb:List of 2
  .. ..$ missense  :'data.frame':	9082 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:9082] "TCGA-02-0047-01" "TCGA-02-0055-01" "TCGA-AB-2805-03" "TCGA-AB-2806-03" ...
  .. .. ..$ mutation: num [1:9082] 56 47 40 422 214 588 14 8 19 8 ...
  .. ..$ truncating:'data.frame':	9082 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:9082] "TCGA-02-0047-01" "TCGA-02-0055-01" "TCGA-AB-2805-03" "TCGA-AB-2806-03" ...
  .. .. ..$ mutation: num [1:9082] 7 3 17 85 47 183 3 3 1 2 ...
 $ sample.class    : Named chr [1:9082] "GBM" "GBM" "LAML" "LAML" ...
  ..- attr(*, "names")= chr [1:9082] "TCGA-02-0047-01" "TCGA-02-0055-01" "TCGA-AB-2805-03" "TCGA-AB-2806-03" ...
 $ alteration.class: Named chr [1:396] "MUT" "MUT" "MUT" "MUT" ...
  ..- attr(*, "names")= chr [1:396] "AKT1" "ALK" "APC" "AR" ...

In [7]:
table(run_data$sample.class)

                   ACC                   BLCA             BRCA_Basal
                    76                    398                    171
             BRCA_Her2              BRCA_LumA              BRCA_LumB
                    78                    499                    197
           BRCA_Normal    CESC_AdenoCarcinoma CESC_SquamousCarcinoma
                    36                     43                    229
                  CHOL                CRC_CIN                 CRC_GS
                    36                    328                     58
               CRC_MSI                   DLBC               ESCA_CIN
                    63                     37                     74
             ESCA_ESCC                    GBM              HNSC_HPV-
                    90                    126                    415
             HNSC_HPV+                   KICH                   KIRC
                    72                     65                    352
                  KIRP                   LAML       LGG_IDHmut-codel
                   271                    162                    167
  LGG_IDHmut-non-codel              LGG_IDHwt                   LIHC
                   248                     92                    348
                  LUAD                   LUSC                   MESO
                   502                    464                     82
                    OV                   PAAD                   PCPG
                   177                    152                    161
                  PRAD             SARC_DDLPS               SARC_LMS
                   479                     46                     83
          SARC_MFS/UPS             SARC_Other                   SKCM
                    80                     20                    363
              STAD_CIN               STAD_EBV                STAD_GS
                   223                     30                     50
              STAD_MSI      TGCT_non-seminoma          TGCT_seminoma
                    73                     82                     62
                  THCA                   THYM           UCEC_CN_HIGH
                   480                    119                    163
           UCEC_CN_LOW               UCEC_MSI              UCEC_POLE
                   147                    144                     33
                   UCS                    UVM
                    56                     80

In [8]:
obj <- selectX( M = run_data$M,
                sample.class = run_data$sample.class,
                alteration.class = run_data$alteration.class,
                n.cores = 30,
                min.freq = (0.001*9082),
                n.permut = 1000,
                lambda = 0.3,
                tao = 1,
                save.object = FALSE,
                verbose = FALSE,
                estimate_pairwise = FALSE,
                maxFDR = 0.25)

Total Time: 246.371 sec elapsed

In [9]:
# Save the result
saveRDS(obj,'../results/pan_can_tcga_run_result.rds')

## TCGA Tumor Type Runs

In [10]:
table(run_data$sample.class)

                   ACC                   BLCA             BRCA_Basal
                    76                    398                    171
             BRCA_Her2              BRCA_LumA              BRCA_LumB
                    78                    499                    197
           BRCA_Normal    CESC_AdenoCarcinoma CESC_SquamousCarcinoma
                    36                     43                    229
                  CHOL                CRC_CIN                 CRC_GS
                    36                    328                     58
               CRC_MSI                   DLBC               ESCA_CIN
                    63                     37                     74
             ESCA_ESCC                    GBM              HNSC_HPV-
                    90                    126                    415
             HNSC_HPV+                   KICH                   KIRC
                    72                     65                    352
                  KIRP                   LAML       LGG_IDHmut-codel
                   271                    162                    167
  LGG_IDHmut-non-codel              LGG_IDHwt                   LIHC
                   248                     92                    348
                  LUAD                   LUSC                   MESO
                   502                    464                     82
                    OV                   PAAD                   PCPG
                   177                    152                    161
                  PRAD             SARC_DDLPS               SARC_LMS
                   479                     46                     83
          SARC_MFS/UPS             SARC_Other                   SKCM
                    80                     20                    363
              STAD_CIN               STAD_EBV                STAD_GS
                   223                     30                     50
              STAD_MSI      TGCT_non-seminoma          TGCT_seminoma
                    73                     82                     62
                  THCA                   THYM           UCEC_CN_HIGH
                   480                    119                    163
           UCEC_CN_LOW               UCEC_MSI              UCEC_POLE
                   147                    144                     33
                   UCS                    UVM
                    56                     80

In [11]:
(all_merged_metdata %>% filter(cohort=='TCGA')) %>% head()

  sample          class tumor_run oncotree cancer_type              race
1 TCGA-OR-A5J5-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
2 TCGA-OR-A5JB-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
3 TCGA-OR-A5JJ-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
4 TCGA-OR-A5JS-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
5 TCGA-OR-A5JY-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
6 TCGA-OR-A5K4-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
  cohort tumor_run_mapped Tissue        final_tumor_run_mapped
1 TCGA   No mapping       Adrenal Gland ACC
2 TCGA   No mapping       Adrenal Gland ACC
3 TCGA   No mapping       Adrenal Gland ACC
4 TCGA   No mapping       Adrenal Gland ACC
5 TCGA   No mapping       Adrenal Gland ACC
6 TCGA   No mapping       Adrenal Gland ACC

In [12]:
(table((all_merged_metdata %>% filter(cohort=='TCGA'))$tumor_run))

      ACC       AML      BLCA    Breast     CCRCC      CESC      CHOL       CRC
       76       162       398       981       352       272        36       449
     DIFG      ESCA        GB       HCC      HNSC      Lung  Lymphoma       MEL
      507       164       126       348       487       966        37       363
   NCCRCC      PAAD      PCPG    PLMESO Prostrate      SARC       SOC      STAD
      336       152       161        82       479       229       177       376
     TGCT      THPA      THYM      UCEC        UM
      144       480       119       543        80

In [13]:
str(run_data)

List of 3
 $ M               :List of 2
  ..$ M  :List of 2
  .. ..$ missense  : num [1:396, 1:9082] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:396] "AKT1" "ALK" "APC" "AR" ...
  .. .. .. ..$ : chr [1:9082] "TCGA-02-0047-01" "TCGA-02-0055-01" "TCGA-AB-2805-03" "TCGA-AB-2806-03" ...
  .. ..$ truncating: num [1:396, 1:9082] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:396] "AKT1" "ALK" "APC" "AR" ...
  .. .. .. ..$ : chr [1:9082] "TCGA-02-0047-01" "TCGA-02-0055-01" "TCGA-AB-2805-03" "TCGA-AB-2806-03" ...
  ..$ tmb:List of 2
  .. ..$ missense  :'data.frame':	9082 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:9082] "TCGA-02-0047-01" "TCGA-02-0055-01" "TCGA-AB-2805-03" "TCGA-AB-2806-03" ...
  .. .. ..$ mutation: num [1:9082] 56 47 40 422 214 588 14 8 19 8 ...
  .. ..$ truncating:'data.frame':	9082 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:9082] "TCGA-02-0047-01" "TCGA-02-0055-01" "TCGA-AB-2805-03" "TCGA-AB-2806-03" ...
  .. .. ..$ mutation: num [1:9082] 7 3 17 85 47 183 3 3 1 2 ...
 $ sample.class    : Named chr [1:9082] "GBM" "GBM" "LAML" "LAML" ...
  ..- attr(*, "names")= chr [1:9082] "TCGA-02-0047-01" "TCGA-02-0055-01" "TCGA-AB-2805-03" "TCGA-AB-2806-03" ...
 $ alteration.class: Named chr [1:396] "MUT" "MUT" "MUT" "MUT" ...
  ..- attr(*, "names")= chr [1:396] "AKT1" "ALK" "APC" "AR" ...

In [14]:
global_sample_covariates <-(all_merged_metdata %>% filter(cohort=='TCGA'))$class
names(global_sample_covariates)<-(all_merged_metdata %>% filter(cohort=='TCGA'))$sample

In [15]:
tumor_run_group <- names((table((all_merged_metdata %>% filter(cohort=='TCGA'))$tumor_run)))

In [16]:
tumor_type_run <- list()
for(i in unique(tumor_run_group)){
    samples <- ((all_merged_metdata %>% filter(cohort=='TCGA')) %>% filter(tumor_run==i))$sample
    print(i)
    gene_to_take <- rownames(run_data$M$M$missense)
    order <- samples
    data <- run_data
    data$M$M$missense <- run_data$M$M$missense[gene_to_take,order]
    data$M$M$truncating <- run_data$M$M$truncating[gene_to_take,order]
    data$M$tmb$missense <- run_data$M$tmb$missense[order,]    
    data$M$tmb$truncating <- run_data$M$tmb$truncating[order,]    

    sample_covariates<-global_sample_covariates[samples]
    data$sample.class<-sample_covariates
    data$alteration.class<-run_data$alteration.class
    tumor_type_run[[i]]<-data
}

[1] "ACC"
[1] "AML"
[1] "BLCA"
[1] "Breast"
[1] "CCRCC"
[1] "CESC"
[1] "CHOL"
[1] "CRC"
[1] "DIFG"
[1] "ESCA"
[1] "GB"
[1] "HCC"
[1] "HNSC"
[1] "Lung"
[1] "Lymphoma"
[1] "MEL"
[1] "NCCRCC"
[1] "PAAD"
[1] "PCPG"
[1] "PLMESO"
[1] "Prostrate"
[1] "SARC"
[1] "SOC"
[1] "STAD"
[1] "TGCT"
[1] "THPA"
[1] "THYM"
[1] "UCEC"
[1] "UM"

In [17]:
length(tumor_type_run)

[1] 29

In [18]:
for(cancer in names(tumor_type_run)){
    filter <- (0.001)*length(tumor_type_run[[cancer]]$sample.class)
    print(paste(cancer,filter))
}

[1] "ACC 0.076"
[1] "AML 0.162"
[1] "BLCA 0.398"
[1] "Breast 0.981"
[1] "CCRCC 0.352"
[1] "CESC 0.272"
[1] "CHOL 0.036"
[1] "CRC 0.449"
[1] "DIFG 0.507"
[1] "ESCA 0.164"
[1] "GB 0.126"
[1] "HCC 0.348"
[1] "HNSC 0.487"
[1] "Lung 0.966"
[1] "Lymphoma 0.037"
[1] "MEL 0.363"
[1] "NCCRCC 0.336"
[1] "PAAD 0.152"
[1] "PCPG 0.161"
[1] "PLMESO 0.082"
[1] "Prostrate 0.479"
[1] "SARC 0.229"
[1] "SOC 0.177"
[1] "STAD 0.376"
[1] "TGCT 0.144"
[1] "THPA 0.48"
[1] "THYM 0.119"
[1] "UCEC 0.543"
[1] "UM 0.08"

In [19]:
for(cancer in names(tumor_type_run)){
    cat('Running:',cancer)
    cat('\n')
    obj <- selectX( M = tumor_type_run[[cancer]]$M,
                sample.class = tumor_type_run[[cancer]]$sample.class,
                alteration.class = tumor_type_run[[cancer]]$alteration.class,
                n.cores = 20,
                min.freq = (0.001*length(tumor_type_run[[cancer]]$sample.class)),
                n.permut = 1000,
                lambda = 0.3,
                tao = 1,
                save.object = FALSE,
                verbose = FALSE,
                estimate_pairwise = FALSE,
                maxFDR = 0.25)

    saveRDS(obj,paste('../results/tcga_',cancer,'.rds',sep=""))
    cat('\n Running done:',cancer)
    cat('\n')
    rm(obj)
}

Running: ACC
Total Time: 4.892 sec elapsed

 Running done: ACC
Running: AML
Total Time: 8.077 sec elapsed

 Running done: AML
Running: BLCA
Total Time: 30.983 sec elapsed

 Running done: BLCA
Running: Breast
Total Time: 45.744 sec elapsed

 Running done: Breast
Running: CCRCC
Total Time: 11.607 sec elapsed

 Running done: CCRCC
Running: CESC
Total Time: 16.092 sec elapsed

 Running done: CESC
Running: CHOL
Total Time: 19.512 sec elapsed

 Running done: CHOL
Running: CRC
Total Time: 33.312 sec elapsed

 Running done: CRC
Running: DIFG
Total Time: 12.693 sec elapsed

 Running done: DIFG
Running: ESCA
Total Time: 9.101 sec elapsed

 Running done: ESCA
Running: GB
Total Time: 7.52 sec elapsed

 Running done: GB
Running: HCC
Total Time: 14.388 sec elapsed

 Running done: HCC
Running: HNSC
Total Time: 23.958 sec elapsed

 Running done: HNSC
Running: Lung
Total Time: 54.513 sec elapsed

 Running done: Lung
Running: Lymphoma
Total Time: 24.914 sec elapsed

 Running done: Lymphoma
Running: MEL
Total Time: 34.791 sec elapsed

 Running done: MEL
Running: NCCRCC
Total Time: 12.3 sec elapsed

 Running done: NCCRCC
Running: PAAD
Total Time: 8.083 sec elapsed

 Running done: PAAD
Running: PCPG
Total Time: 19.447 sec elapsed

 Running done: PCPG
Running: PLMESO
Total Time: 24.716 sec elapsed

 Running done: PLMESO
Running: Prostrate
Total Time: 12.193 sec elapsed

 Running done: Prostrate
Running: SARC
Total Time: 7.951 sec elapsed

 Running done: SARC
Running: SOC
Total Time: 8.027 sec elapsed

 Running done: SOC
Running: STAD
Total Time: 33.327 sec elapsed

 Running done: STAD
Running: TGCT
Total Time: 5.858 sec elapsed

 Running done: TGCT
Running: THPA
Total Time: 7.582 sec elapsed

 Running done: THPA
Running: THYM
Total Time: 4.175 sec elapsed

 Running done: THYM
Running: UCEC
Total Time: 63.785 sec elapsed

 Running done: UCEC
Running: UM
Total Time: 26.126 sec elapsed

 Running done: UM