In [1]:
library('tidyverse')
library('SelectSim')

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
sessionInfo()

R version 4.4.2 (2024-10-31)
Platform: x86_64-conda-linux-gnu
Running under: AlmaLinux 9.3 (Shamrock Pampas Cat)

Matrix products: default
BLAS/LAPACK: /mnt/ndata/arvind/envs/selectsim_R/lib/libopenblasp-r0.3.29.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Europe/Zurich
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] SelectSim_0.0.1.5 lubridate_1.9.4   forcats_1.0.0     stringr_1.5.1
 [5] dplyr_1.1.4       purrr_1.0.4       readr_2.1.5       tidyr_1.3.1
 [9] tibble_3.2.1      ggplot2_3.5.1     tidyverse_2.0.0

loaded via a namespace (and not attached):
 [1] gtable_0.3.6       rstatix_0.7.2      lattice_0.22-6     tzdb_0.5.0
 [5] vctrs_0.6.5        tools_4.4.2        generics_0.1.3     parallel_4.4.2
 [9] pkgconfig_2.0.3    Matrix_1.7-3       ggridges_0.5.6     rngtools_1.5.2
[13] RcppParallel_5.1.9 uuid_1.2-1         lifecycle_1.0.4    compiler_4.4.2
[17] tictoc_1.2.1       munsell_0.5.1      repr_1.1.7         codetools_0.2-20
[21] carData_3.0-5      htmltools_0.5.8.1  Formula_1.2-5      pillar_1.10.1
[25] car_3.1-3          ggpubr_0.6.0       crayon_1.5.3       doRNG_1.8.6.2
[29] iterators_1.0.14   abind_1.4-5        foreach_1.5.2      tidyselect_1.2.1
[33] digest_0.6.37      stringi_1.8.7      reshape2_1.4.4     fastmap_1.2.0
[37] grid_4.4.2         colorspace_2.1-1   cli_3.6.4          magrittr_2.0.3
[41] base64enc_0.1-3    Rfast_2.1.0        IRdisplay_1.1      broom_1.0.8
[45] withr_3.0.2        scales_1.3.0       backports_1.5.0    IRkernel_1.3.2
[49] RcppZiggurat_0.1.8 timechange_0.3.0   pbdZMQ_0.3-13      ggsignif_0.6.4
[53] hms_1.1.3          evaluate_1.0.3     doParallel_1.0.17  rlang_1.1.5
[57] Rcpp_1.0.14        glue_1.8.0         jsonlite_2.0.0     R6_2.6.1
[61] plyr_1.8.9

# Metadata

In [3]:
all_merged_metdata <- readRDS(file='/mnt/ndata/arvind/co_mutation_project/data/processed/all_merged_data_genie_v15.rds')

# TCGA

In [6]:
pan_can <- readRDS('/mnt/ndata/arvind/co_mutation_project_revision/catalogue/results/pan_can_tcga_run_result.rds')

In [7]:
pan_can$result %>% dplyr::count(FDR)

  FDR   n
1 FALSE 52094
2  TRUE   232

In [8]:
pan_can_result <- pan_can$result

In [9]:
rm(pan_can)

In [10]:
pan_can_result %>% filter(FDR) %>% dplyr::count(type)

  type n
1 CO    80
2 ME   152

In [11]:
head(pan_can_result)

              SFE_1  SFE_2 name          support_1 support_2 freq_1
PIK3CA - TP53 PIK3CA TP53  PIK3CA - TP53 1136      3030      0.12508258
BRAF - TP53   BRAF   TP53  BRAF - TP53    611      3030      0.06727593
ARID1A - TP53 ARID1A TP53  ARID1A - TP53  571      3030      0.06287161
BRAF - NRAS   BRAF   NRAS  BRAF - NRAS    611       240      0.06727593
CDKN2A - TP53 CDKN2A TP53  CDKN2A - TP53  334      3030      0.03677604
PTEN - TP53   PTEN   TP53  PTEN - TP53    635      3030      0.06991852
              freq_2    overlap w_overlap  max_overlap ⋯ w_r_overlap wES
PIK3CA - TP53 0.3336270 357     317.529713 669         ⋯ 392.6257    -53.10086
BRAF - TP53   0.3336270  82      53.397547 180         ⋯ 122.3579    -48.76234
ARID1A - TP53 0.3336270 147     115.192451 371         ⋯ 170.2782    -38.95153
BRAF - NRAS   0.0264259  13       6.352379 191         ⋯  54.8161    -34.26902
CDKN2A - TP53 0.3336270 225     202.011705 334         ⋯ 154.2020     33.80660
PTEN - TP53   0.3336270 158     133.797790 385         ⋯ 181.7601    -33.91445
              wFDR nES       mean_r_nES nFDR cum_freq nFDR2 type FDR
PIK3CA - TP53 0    -45.60861 -7.492254  0    4166     0     ME   TRUE
BRAF - TP53   0    -44.07050 -4.691847  0    3641     0     ME   TRUE
ARID1A - TP53 0    -34.04462 -4.906915  0    3601     0     ME   TRUE
BRAF - NRAS   0    -31.41637 -2.852654  0     851     0     ME   TRUE
CDKN2A - TP53 0     29.36254  4.444063  0    3364     0     CO   TRUE
PTEN - TP53   0    -28.40808 -5.506369  0    3665     0     ME   TRUE

In [13]:
pan_can_result$datatype <- 'Pan-can'
pan_can_result$cohort <- 'TCGA'

In [14]:
head(all_merged_metdata)

  sample          class tumor_run oncotree cancer_type              race
1 TCGA-OR-A5J5-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
2 TCGA-OR-A5JB-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
3 TCGA-OR-A5JJ-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
4 TCGA-OR-A5JS-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
5 TCGA-OR-A5JY-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
6 TCGA-OR-A5K4-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
  cohort tumor_run_mapped Tissue        final_tumor_run_mapped
1 TCGA   No mapping       Adrenal Gland ACC
2 TCGA   No mapping       Adrenal Gland ACC
3 TCGA   No mapping       Adrenal Gland ACC
4 TCGA   No mapping       Adrenal Gland ACC
5 TCGA   No mapping       Adrenal Gland ACC
6 TCGA   No mapping       Adrenal Gland ACC

In [15]:
(table((all_merged_metdata %>% filter(cohort=='TCGA'))$tumor_run))

      ACC       AML      BLCA    Breast     CCRCC      CESC      CHOL       CRC
       76       162       398       981       352       272        36       449
     DIFG      ESCA        GB       HCC      HNSC      Lung  Lymphoma       MEL
      507       164       126       348       487       966        37       363
   NCCRCC      PAAD      PCPG    PLMESO Prostrate      SARC       SOC      STAD
      336       152       161        82       479       229       177       376
     TGCT      THPA      THYM      UCEC        UM
      144       480       119       543        80

In [16]:
tumor_type_run <- list()
for(i in unique((all_merged_metdata %>% filter(cohort=='TCGA'))$tumor_run)){
    print(i)
    tumor_type_run[[i]]<-(readRDS(paste('/mnt/ndata/arvind/co_mutation_project_revision/catalogue/results/tcga_',i,'.rds',sep="")))$result
    tumor_type_run[[i]]$datatype <- i
    tumor_type_run[[i]]$cohort  <- 'TCGA'
}

[1] "ACC"
[1] "BLCA"
[1] "Breast"
[1] "CESC"
[1] "CHOL"
[1] "CRC"
[1] "Lymphoma"
[1] "ESCA"
[1] "GB"
[1] "HNSC"
[1] "NCCRCC"
[1] "CCRCC"
[1] "AML"
[1] "DIFG"
[1] "HCC"
[1] "Lung"
[1] "PLMESO"
[1] "SOC"
[1] "PAAD"
[1] "PCPG"
[1] "Prostrate"
[1] "SARC"
[1] "MEL"
[1] "STAD"
[1] "TGCT"
[1] "THPA"
[1] "THYM"
[1] "UCEC"
[1] "UM"

In [17]:
length(tumor_type_run)

[1] 29

In [18]:
merged_df <- bind_rows(tumor_type_run)

In [20]:
final_merge<- bind_rows(pan_can_result,merged_df)

In [21]:
dim(final_merge)

[1] 479451     24

In [22]:
head(final_merge)

                  SFE_1  SFE_2 name          support_1 support_2 freq_1
PIK3CA - TP53...1 PIK3CA TP53  PIK3CA - TP53 1136      3030      0.12508258
BRAF - TP53...2   BRAF   TP53  BRAF - TP53    611      3030      0.06727593
ARID1A - TP53...3 ARID1A TP53  ARID1A - TP53  571      3030      0.06287161
BRAF - NRAS...4   BRAF   NRAS  BRAF - NRAS    611       240      0.06727593
CDKN2A - TP53...5 CDKN2A TP53  CDKN2A - TP53  334      3030      0.03677604
PTEN - TP53...6   PTEN   TP53  PTEN - TP53    635      3030      0.06991852
                  freq_2    overlap w_overlap  max_overlap ⋯ wFDR nES
PIK3CA - TP53...1 0.3336270 357     317.529713 669         ⋯ 0    -45.60861
BRAF - TP53...2   0.3336270  82      53.397547 180         ⋯ 0    -44.07050
ARID1A - TP53...3 0.3336270 147     115.192451 371         ⋯ 0    -34.04462
BRAF - NRAS...4   0.0264259  13       6.352379 191         ⋯ 0    -31.41637
CDKN2A - TP53...5 0.3336270 225     202.011705 334         ⋯ 0     29.36254
PTEN - TP53...6   0.3336270 158     133.797790 385         ⋯ 0    -28.40808
                  mean_r_nES nFDR cum_freq nFDR2 type FDR  datatype cohort
PIK3CA - TP53...1 -7.492254  0    4166     0     ME   TRUE Pan-can  TCGA
BRAF - TP53...2   -4.691847  0    3641     0     ME   TRUE Pan-can  TCGA
ARID1A - TP53...3 -4.906915  0    3601     0     ME   TRUE Pan-can  TCGA
BRAF - NRAS...4   -2.852654  0     851     0     ME   TRUE Pan-can  TCGA
CDKN2A - TP53...5  4.444063  0    3364     0     CO   TRUE Pan-can  TCGA
PTEN - TP53...6   -5.506369  0    3665     0     ME   TRUE Pan-can  TCGA

In [23]:
rownames(final_merge)<- c(1:nrow(final_merge))

In [24]:
dim(final_merge)

[1] 479451     24

In [25]:
saveRDS(final_merge,file='/mnt/ndata/arvind/co_mutation_project_revision/catalogue/results/tcga_merged_result.rds')